import { database } from "@/lib/d1-auth";
import { maintenanceRunKey, nextMaintenanceDue } from "@/lib/p2-operations-policy";

type PlanRow = { id:string; name:string; assetId:string; assetName:string; location:string; organization:string; recurrenceDays:number; nextDueAt:number; templateId:string|null; createdBy:string; requesterRole:string };

export async function POST(request:Request){
  const secret=process.env.P2_CRON_SECRET; if(!secret||request.headers.get("authorization")!==`Bearer ${secret}`)return Response.json({error:"CRON_UNAUTHORIZED"},{status:401});
  const db=await database(),now=Math.floor(Date.now()/1000),plans=(await db.prepare("SELECT mp.id,mp.name,mp.asset_id AS assetId,a.name AS assetName,a.location,a.organization,mp.recurrence_days AS recurrenceDays,mp.next_due_at AS nextDueAt,mp.template_id AS templateId,mp.created_by AS createdBy,u.role AS requesterRole FROM maintenance_plans mp JOIN assets a ON a.id=mp.asset_id JOIN users u ON u.id=mp.created_by WHERE mp.status='active' AND mp.next_due_at<=?+mp.booking_window_days*86400 ORDER BY mp.next_due_at LIMIT 50").bind(now).all<PlanRow>()).results;let generated=0,idempotent=0;
  for(const plan of plans){const key=maintenanceRunKey(plan.id,plan.nextDueAt);if(await db.prepare("SELECT id FROM maintenance_plan_runs WHERE idempotency_key=?").bind(key).first()){idempotent+=1;continue;}const draftId=crypto.randomUUID(),requestId=crypto.randomUUID(),workOrderId=crypto.randomUUID(),runId=crypto.randomUUID(),nextDueAt=nextMaintenanceDue(plan.nextDueAt,plan.recurrenceDays),title=`PM · ${plan.assetName}`,details=`Sinh tự động từ ${plan.name}; kỳ ${plan.nextDueAt}`;const statements=[db.prepare("INSERT INTO service_drafts (id,owner_id,service_type,title,details,status,version,confirmed_version,created_at,updated_at) VALUES (?,?, 'support',?,?,'submitted',1,1,?,?)").bind(draftId,plan.createdBy,title,details,now,now),db.prepare("INSERT INTO service_requests (id,draft_id,owner_id,organization,service_type,title,details,status,target_department,requester_role,visibility,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,'support',?,?,'in_progress','facility',?,'internal',?,?,?)").bind(requestId,draftId,plan.createdBy,plan.organization,title,details,plan.requesterRole,key,now,now),db.prepare("INSERT INTO maintenance_work_orders (id,request_id,title,location,priority,status,asset_id,maintenance_plan_id,created_by,created_at,updated_at) VALUES (?,?,?,?, 'normal','scheduled',?,?,?,?,?)").bind(workOrderId,requestId,title,plan.location,plan.assetId,plan.id,plan.createdBy,now,now),db.prepare("INSERT INTO maintenance_plan_runs (id,plan_id,due_at,work_order_id,idempotency_key,created_at) VALUES (?,?,?,?,?,?)").bind(runId,plan.id,plan.nextDueAt,workOrderId,key,now),db.prepare("UPDATE maintenance_plans SET next_due_at=?,updated_at=? WHERE id=? AND next_due_at=?").bind(nextDueAt,now,plan.id,plan.nextDueAt),db.prepare("INSERT INTO notifications (id,recipient_id,type,entity_type,entity_id,dedupe_key,title,body,created_at) SELECT lower(hex(randomblob(16))),u.id,'maintenance_due','maintenance_plan',?,?||':'||u.id,'Đã sinh work order bảo trì',?,? FROM users u WHERE u.role='facility_manager' ON CONFLICT(dedupe_key) DO NOTHING").bind(plan.id,key,`${plan.assetName} · hạn ${plan.nextDueAt}`,now),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),plan.createdBy,"maintenance_plan.auto_generated","maintenance_plan_run",runId,JSON.stringify({planId:plan.id,workOrderId,dueAt:plan.nextDueAt,nextDueAt}),now)];if(plan.templateId)statements.push(db.prepare("INSERT INTO work_order_tasks (id,work_order_id,template_task_id,sequence,title,required,status,updated_at) SELECT lower(hex(randomblob(16))),?,id,sequence,title,required,'pending',? FROM operation_template_tasks WHERE template_id=? ORDER BY sequence").bind(workOrderId,now,plan.templateId));try{await db.batch(statements);generated+=1;}catch{idempotent+=1;}}
  const warranties=(await db.prepare("SELECT id,name,warranty_end AS warrantyEnd FROM assets WHERE status<>'retired' AND warranty_end BETWEEN ? AND ?").bind(now,now+30*86400).all<{id:string;name:string;warrantyEnd:number}>()).results;for(const asset of warranties)await db.prepare("INSERT INTO notifications (id,recipient_id,type,entity_type,entity_id,dedupe_key,title,body,created_at) SELECT lower(hex(randomblob(16))),u.id,'warranty_warning','asset',?,?||':'||u.id,'Bảo hành sắp hết hạn',?,? FROM users u WHERE u.role='facility_manager' ON CONFLICT(dedupe_key) DO NOTHING").bind(asset.id,`warranty:${asset.id}:${asset.warrantyEnd}`,`${asset.name} · ${asset.warrantyEnd}`,now).run();
  return Response.json({processed:plans.length,generated,idempotent,warrantyWarnings:warranties.length,ranAt:now});
}
