import { database, sha256 } from "@/lib/d1-auth";
import { retentionCutoff } from "@/lib/enterprise-policy";
import { incidentStatement, observedJson, recordOperationalEvent, requestContext } from "@/lib/observability";

type Candidate={dataClass:"auth_session"|"visitor_qr"|"observability";entityType:string;entityId:string;payload:Record<string,unknown>;held:boolean};

export async function POST(request:Request){
  const ctx=requestContext(request),secret=process.env.RETENTION_CRON_SECRET;
  if(!secret||request.headers.get("authorization")!==`Bearer ${secret}`)return observedJson({error:"CRON_UNAUTHORIZED"},401,ctx.correlationId,ctx.traceId);
  const body=await request.json().catch(()=>({})) as {dryRun?:boolean},dryRun=body.dryRun!==false,db=await database(),now=Math.floor(Date.now()/1000),runId=crypto.randomUUID();
  await db.prepare("INSERT INTO retention_job_runs (id,correlation_id,dry_run,status,started_at) VALUES (?,?,?,'running',?)").bind(runId,ctx.correlationId,dryRun?1:0,now).run();
  try{
    const policies=(await db.prepare("SELECT data_class AS dataClass,retention_days AS retentionDays,action FROM retention_policies WHERE status='active'").all<{dataClass:string;retentionDays:number;action:string}>()).results,candidates:Candidate[]=[];
    for(const policy of policies){const cutoff=retentionCutoff(now,policy.retentionDays);if(policy.dataClass==="auth_session"){const rows=(await db.prepare("SELECT s.id,s.expires_at AS expiresAt,EXISTS(SELECT 1 FROM legal_holds h WHERE h.entity_type='session' AND h.entity_id=s.id AND h.status='active') AS held FROM sessions s WHERE s.expires_at<? LIMIT 500").bind(cutoff).all<{id:string;expiresAt:number;held:number}>()).results;for(const row of rows)candidates.push({dataClass:"auth_session",entityType:"session",entityId:row.id,payload:{id:row.id,expiresAt:row.expiresAt},held:row.held===1});}if(policy.dataClass==="visitor_qr"){const rows=(await db.prepare("SELECT q.id,q.visitor_id AS visitorId,q.expires_at AS expiresAt,q.redeemed_at AS redeemedAt,EXISTS(SELECT 1 FROM legal_holds h WHERE h.entity_type='visitor_qr_token' AND h.entity_id=q.id AND h.status='active') AS held FROM visitor_qr_tokens q WHERE q.expires_at<? LIMIT 500").bind(cutoff).all<{id:string;visitorId:string;expiresAt:number;redeemedAt:number|null;held:number}>()).results;for(const row of rows)candidates.push({dataClass:"visitor_qr",entityType:"visitor_qr_token",entityId:row.id,payload:{id:row.id,visitorId:row.visitorId,expiresAt:row.expiresAt,redeemedAt:row.redeemedAt},held:row.held===1});}if(policy.dataClass==="observability"){const rows=(await db.prepare("SELECT id,correlation_id AS correlationId,event_name AS eventName,created_at AS createdAt,EXISTS(SELECT 1 FROM legal_holds h WHERE h.entity_type='observability_event' AND h.entity_id=observability_events.id AND h.status='active') AS held FROM observability_events WHERE created_at<? LIMIT 500").bind(cutoff).all<{id:string;correlationId:string;eventName:string;createdAt:number;held:number}>()).results;for(const row of rows)candidates.push({dataClass:"observability",entityType:"observability_event",entityId:row.id,payload:row,held:row.held===1});}}
    const held=candidates.filter(value=>value.held),processable=candidates.filter(value=>!value.held);let processed=0;
    if(!dryRun){for(const candidate of processable){const statements=[];if(candidate.dataClass==="visitor_qr"){const payload=JSON.stringify(candidate.payload);statements.push(db.prepare("INSERT INTO retention_archive (id,job_run_id,data_class,entity_type,entity_id,payload,payload_hash,archived_at) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),runId,candidate.dataClass,candidate.entityType,candidate.entityId,payload,await sha256(payload),now));}const table=candidate.dataClass==="auth_session"?"sessions":candidate.dataClass==="visitor_qr"?"visitor_qr_tokens":"observability_events";statements.push(db.prepare(`DELETE FROM ${table} WHERE id=?`).bind(candidate.entityId));await db.batch(statements);processed+=1;}}
    await db.batch([db.prepare("UPDATE retention_job_runs SET status='completed',candidate_count=?,processed_count=?,held_count=?,completed_at=? WHERE id=?").bind(candidates.length,processed,held.length,now,runId),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,correlation_id,source,created_at) VALUES (?,'demo-system-admin-001','data_retention.completed','retention_job_run',?,?,?,'retention_cron',?)").bind(crypto.randomUUID(),runId,JSON.stringify({dryRun,candidates:candidates.length,processed,held:held.length}),ctx.correlationId,now)]);
    await recordOperationalEvent(db,{...ctx,level:"info",eventName:"retention.completed",route:"/api/cron/retention",statusCode:200,metadata:{dryRun,candidateCount:candidates.length,processedCount:processed,heldCount:held.length}});
    return observedJson({runId,dryRun,candidateCount:candidates.length,processedCount:processed,heldCount:held.length},200,ctx.correlationId,ctx.traceId);
  }catch(error){const code=error instanceof Error?error.message.slice(0,100):"RETENTION_FAILED";await db.batch([db.prepare("UPDATE retention_job_runs SET status='failed',error_code=?,completed_at=? WHERE id=?").bind(code,now,runId),incidentStatement(db,{correlationId:ctx.correlationId,source:"retention.job",severity:"critical",title:"Retention job thất bại",runbook:"docs/runbooks/retention-failure.md",dedupeKey:`retention:${Math.floor(now/86400)}`,now})]);await recordOperationalEvent(db,{...ctx,level:"error",eventName:"retention.failed",route:"/api/cron/retention",statusCode:500,errorCode:code});return observedJson({error:"RETENTION_FAILED",runId},500,ctx.correlationId,ctx.traceId)}
}
