"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type User={id:string;fullName:string;role:string;organization:string;departmentCode:string|null;capabilities:string[]};
type Staff={id:string;fullName:string;role:string};
type OpsRequest={id:string;serviceType:string;title:string;details:string;status:string;targetDepartment:string;assignedTo:string|null;requesterName:string;assigneeName:string|null;createdAt:number;updatedAt:number};
type Booking={id:string;title:string;startsAt:number;endsAt:number;attendeeCount:number;status:string;spaceName:string;requesterName:string};
type WorkOrder={id:string;requestId:string;title:string;location:string;priority:string;status:string;assignedTo:string|null;assigneeName:string|null;scheduledAt:number|null;resolution:string;updatedAt:number};
type Dashboard={department:string;requests:OpsRequest[];staff:Staff[];bookings:Booking[];workOrders:WorkOrder[]};

const statusLabels:Record<string,string>={submitted:"Mới tiếp nhận",triaged:"Đã phân loại",in_progress:"Đang xử lý",waiting_customer:"Chờ khách hàng",resolved:"Đã hoàn tất",cancelled:"Đã hủy",open:"Mở",scheduled:"Đã lên lịch",completed:"Hoàn thành"};
const roleLabels:Record<string,string>={service_desk:"Service Desk",facility_staff:"Nhân viên Facility",facility_manager:"Quản lý Facility"};
function csrfHeaders(extra:Record<string,string>={}){const token=document.cookie.split(";").map(v=>v.trim()).find(v=>v.startsWith("nic_csrf="))?.slice(9)??"";return{...extra,"X-CSRF-Token":decodeURIComponent(token)};}
async function payload(response:Response){const text=await response.text();try{return text?JSON.parse(text):{};}catch{return{};}}
function dateTime(value:number|null){return value?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(value*1000):"Chưa lên lịch";}

export function OperationsDashboard(){
  const[user,setUser]=useState<User|null>(null);const[data,setData]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[filter,setFilter]=useState("active");const[selected,setSelected]=useState<OpsRequest|null>(null);const[workOrderRequest,setWorkOrderRequest]=useState<OpsRequest|null>(null);const[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{const session=await fetch("/api/auth/session");if(session.status===401){location.href="/auth";return;}const current=(await session.json()).user as User;setUser(current);const response=await fetch("/api/operations/dashboard");const body=await payload(response);if(!response.ok)throw new Error(response.status===403?"Tài khoản không có quyền truy cập dashboard vận hành.":body.error??"Không tải được dữ liệu.");setData(body);}catch(reason){setError(reason instanceof Error?reason.message:"Không tải được dữ liệu.");}finally{setLoading(false);}},[]);
  useEffect(()=>{fetch("/api/auth/session").then(async session=>{if(session.status===401){location.href="/auth";return;}const current=(await session.json()).user as User;setUser(current);const response=await fetch("/api/operations/dashboard");const body=await payload(response);if(!response.ok)throw new Error(response.status===403?"Tài khoản không có quyền truy cập dashboard vận hành.":body.error??"Không tải được dữ liệu.");setData(body);}).catch(reason=>setError(reason instanceof Error?reason.message:"Không tải được dữ liệu.")).finally(()=>setLoading(false));},[]);
  const visible=useMemo(()=>data?.requests.filter(item=>filter==="all"||(filter==="active"?!["resolved","cancelled"].includes(item.status):item.status===filter))??[],[data,filter]);
  async function updateRequest(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setSaving(true);setError("");const form=new FormData(event.currentTarget);const response=await fetch(`/api/operations/requests/${selected.id}`,{method:"PATCH",headers:csrfHeaders({"Content-Type":"application/json"}),body:JSON.stringify({status:form.get("status"),assignedTo:form.get("assignedTo")||null})});const body=await payload(response);setSaving(false);if(!response.ok)return setError(body.error??"Không thể cập nhật yêu cầu.");setSelected(null);await load();}
  async function createWorkOrder(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!workOrderRequest)return;setSaving(true);setError("");const form=new FormData(event.currentTarget);const scheduled=String(form.get("scheduledAt")??"");const response=await fetch("/api/work-orders",{method:"POST",headers:csrfHeaders({"Content-Type":"application/json"}),body:JSON.stringify({requestId:workOrderRequest.id,title:form.get("title"),location:form.get("location"),priority:form.get("priority"),assignedTo:form.get("assignedTo")||null,scheduledAt:scheduled?Math.floor(new Date(scheduled).getTime()/1000):null})});const body=await payload(response);setSaving(false);if(!response.ok)return setError(body.error??"Không thể tạo work order.");setWorkOrderRequest(null);await load();}
  async function updateWorkOrder(id:string,status:string){const resolution=status==="completed"?prompt("Nhập kết quả xử lý trước khi hoàn thành:")??"":"";if(status==="completed"&&!resolution.trim())return;setSaving(true);const response=await fetch(`/api/work-orders/${id}`,{method:"PATCH",headers:csrfHeaders({"Content-Type":"application/json"}),body:JSON.stringify({status,resolution})});const body=await payload(response);setSaving(false);if(!response.ok)return setError(body.error??"Không thể cập nhật work order.");await load();}
  if(loading)return <main className="ops-loading" aria-busy="true"><div/><div/><div/></main>;
  if(!data||!user)return <main className="ops-error"><h1>Không thể mở bảng vận hành</h1><p>{error}</p><button onClick={()=>{setLoading(true);void load();}}>Thử lại</button></main>;
  const active=data.requests.filter(r=>!["resolved","cancelled"].includes(r.status));const unassigned=active.filter(r=>!r.assignedTo);const waiting=active.filter(r=>r.status==="waiting_customer");
  return <main className="ops-shell">
    <header className="ops-header"><a href="/portal" className="ops-brand"><Image src="/nic-logo.png" alt="NIC" width={128} height={48} unoptimized/><span><strong>Operations</strong><small>{data.department==="facility"?"Facility Command":"Service Desk"}</small></span></a><nav><a className="active" href="/portal/operations">Hàng đợi</a>{data.department==="facility"&&<><a href="#work-orders">Work order</a><a href="#bookings">Lịch không gian</a></>}</nav><div><span>{roleLabels[user.role]??user.role}</span><strong>{user.fullName}</strong></div></header>
    <section className="ops-main"><header className="ops-title"><div><span>NIC · VẬN HÀNH</span><h1>{data.department==="facility"?"Facility Command":"Service Desk"}</h1><p>Tiếp nhận, phân công và điều phối yêu cầu theo đúng phạm vi phòng ban.</p></div><button onClick={()=>void load()} disabled={saving}>Làm mới dữ liệu</button></header>
      {error&&<div className="ops-alert" role="alert">{error}<button onClick={()=>setError("")}>Đóng</button></div>}
      <section className="ops-metrics" aria-label="Tổng quan"><article><span>ĐANG MỞ</span><strong>{active.length}</strong><small>Yêu cầu cần xử lý</small></article><article><span>CHƯA PHÂN CÔNG</span><strong>{unassigned.length}</strong><small>Cần điều phối ngay</small></article><article><span>CHỜ PHẢN HỒI</span><strong>{waiting.length}</strong><small>Từ khách hàng</small></article>{data.department==="facility"&&<article><span>WORK ORDER</span><strong>{data.workOrders.filter(w=>!["completed","cancelled"].includes(w.status)).length}</strong><small>Đang thực hiện</small></article>}</section>
      <section className="ops-board"><div className="ops-section-head"><div><span>REQUEST QUEUE</span><h2>Hàng đợi của đội</h2></div><div className="ops-filters">{[["active","Đang mở"],["submitted","Mới"],["in_progress","Đang xử lý"],["all","Tất cả"]].map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div></div>
        <div className="ops-table"><div className="ops-table-head"><span>Yêu cầu</span><span>Người gửi</span><span>Phụ trách</span><span>Trạng thái</span><span/></div>{visible.length===0?<div className="ops-empty"><strong>Không có yêu cầu trong bộ lọc này</strong><span>Dữ liệu mới sẽ xuất hiện tại đây.</span></div>:visible.map(item=><article key={item.id}><div><small>{item.id.slice(0,8).toUpperCase()} · {item.serviceType}</small><strong>{item.title}</strong><span>{item.details.split("\n")[0]}</span></div><span>{item.requesterName}</span><span>{item.assigneeName??"Chưa phân công"}</span><b data-status={item.status}>{statusLabels[item.status]??item.status}</b><div><button onClick={()=>setSelected(item)}>Cập nhật</button>{data.department==="facility"&&!["resolved","cancelled"].includes(item.status)&&<button onClick={()=>setWorkOrderRequest(item)}>Tạo WO</button>}</div></article>)}</div>
      </section>
      {data.department==="facility"&&<div className="ops-lower"><section id="work-orders" className="ops-subpanel"><div className="ops-section-head"><div><span>MAINTENANCE</span><h2>Work order</h2></div></div><div className="work-order-list">{data.workOrders.length===0?<div className="ops-empty"><strong>Chưa có work order</strong><span>Tạo từ một yêu cầu Facility trong hàng đợi.</span></div>:data.workOrders.map(order=><article key={order.id}><div><span data-priority={order.priority}>{order.priority}</span><strong>{order.title}</strong><small>{order.location} · {order.assigneeName??"Chưa phân công"}</small></div><div><b data-status={order.status}>{statusLabels[order.status]??order.status}</b><small>{dateTime(order.scheduledAt)}</small></div>{!["completed","cancelled"].includes(order.status)&&<select aria-label={`Cập nhật ${order.title}`} value={order.status} disabled={saving} onChange={event=>void updateWorkOrder(order.id,event.target.value)}><option value={order.status}>{statusLabels[order.status]}</option>{order.status==="open"&&<><option value="scheduled">Đã lên lịch</option><option value="in_progress">Bắt đầu xử lý</option></>}{order.status==="scheduled"&&<option value="in_progress">Bắt đầu xử lý</option>}{order.status==="in_progress"&&<option value="completed">Hoàn thành</option>}<option value="cancelled">Hủy</option></select>}</article>)}</div></section>
        <section id="bookings" className="ops-subpanel"><div className="ops-section-head"><div><span>SPACE SCHEDULE</span><h2>Lịch sắp tới</h2></div><a href="/portal/bookings">Mở lịch đặt chỗ</a></div><div className="booking-agenda">{data.bookings.slice(0,8).map(booking=><article key={booking.id}><time><strong>{new Date(booking.startsAt*1000).getDate()}</strong><span>TH {new Date(booking.startsAt*1000).getMonth()+1}</span></time><div><strong>{booking.title}</strong><span>{booking.spaceName} · {booking.attendeeCount} người</span><small>{dateTime(booking.startsAt)} — {new Date(booking.endsAt*1000).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</small></div></article>)}</div></section></div>}
    </section>
    {selected&&<div className="ops-modal-layer" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><form className="ops-modal" onSubmit={updateRequest}><header><div><span>CẬP NHẬT REQUEST</span><h2>{selected.title}</h2></div><button type="button" onClick={()=>setSelected(null)}>Đóng</button></header><label>Phụ trách<select name="assignedTo" defaultValue={selected.assignedTo??""}><option value="">Chưa phân công</option>{data.staff.map(staff=><option value={staff.id} key={staff.id}>{staff.fullName}</option>)}</select></label><label>Trạng thái<select name="status" defaultValue={selected.status}>{["submitted","triaged","in_progress","waiting_customer","resolved","cancelled"].map(status=><option value={status} key={status}>{statusLabels[status]}</option>)}</select></label><button disabled={saving}>{saving?"Đang lưu...":"Lưu cập nhật"}</button></form></div>}
    {workOrderRequest&&<div className="ops-modal-layer" onMouseDown={e=>e.target===e.currentTarget&&setWorkOrderRequest(null)}><form className="ops-modal" onSubmit={createWorkOrder}><header><div><span>MAINTENANCE WORK ORDER</span><h2>Tạo lệnh công việc</h2></div><button type="button" onClick={()=>setWorkOrderRequest(null)}>Đóng</button></header><label>Tiêu đề<input name="title" defaultValue={workOrderRequest.title} required minLength={3}/></label><label>Vị trí<input name="location" required placeholder="Tòa nhà, tầng, phòng"/></label><div className="ops-form-grid"><label>Ưu tiên<select name="priority" defaultValue="normal"><option value="low">Thấp</option><option value="normal">Thông thường</option><option value="high">Cao</option><option value="critical">Khẩn cấp</option></select></label><label>Phụ trách<select name="assignedTo" defaultValue=""><option value="">Chưa phân công</option>{data.staff.map(staff=><option value={staff.id} key={staff.id}>{staff.fullName}</option>)}</select></label></div><label>Lịch thực hiện<input name="scheduledAt" type="datetime-local"/></label><button disabled={saving}>{saving?"Đang tạo...":"Tạo work order"}</button></form></div>}
  </main>;
}
