"use client";
import Image from "next/image";
import { FormEvent,useCallback,useEffect,useState } from "react";
type Row=Record<string,unknown>;
type Data={role:string;permissions:Record<string,boolean>;assets:Row[];plans:Row[];costs:Row[];eventTemplates:Row[];events:Row[];eventTasks:Row[];visitors:Row[];zones:Row[];badgeJobs:Row[];masterRecords:Row[];analytics:{timezone:string;refreshedAt:number;sla:Row;mttr:Row;providers:Row[];costs:Row[];quality:Row;drilldown:Row[]}};
const csrf=()=>({"Content-Type":"application/json","X-CSRF-Token":decodeURIComponent(document.cookie.split(";").map(v=>v.trim()).find(v=>v.startsWith("nic_csrf="))?.slice(9)??"")});
const when=(value:unknown)=>typeof value==="number"?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(value*1000):"—";
const money=(value:unknown,currency="VND")=>new Intl.NumberFormat("vi-VN",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value??0));
export function P2OperationsCenter(){
  const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("assets");
  const load=useCallback(async()=>{const response=await fetch("/api/operations/p2");if(response.status===401){location.href="/auth";return}const body=await response.json();if(!response.ok)throw new Error(body.error??"Không tải được P2 Control Center");setData(body)},[]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{load().catch(reason=>setError(reason instanceof Error?reason.message:"Không tải được dữ liệu"))},[load]);
  async function act(payload:Row){setBusy(true);setError("");setNotice("");const response=await fetch("/api/operations/p2",{method:"POST",headers:csrf(),body:JSON.stringify(payload)}),body=await response.json();setBusy(false);if(!response.ok){setError(body.error??"Không thể thực hiện");return null}setNotice(body.qrToken?`QR dùng một lần: ${body.qrToken}`:"Đã cập nhật và ghi audit.");await load();return body}
  async function createAsset(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(await act({action:"asset_create",code:form.get("code"),name:form.get("name"),location:form.get("location"),category:form.get("category"),parentAssetId:form.get("parentAssetId")||null,serialNumber:form.get("serialNumber"),model:form.get("model"),warrantyEnd:form.get("warrantyEnd")?Math.floor(new Date(String(form.get("warrantyEnd"))).getTime()/1000):null}))event.currentTarget.reset()}
  async function createEvent(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(await act({action:"event_from_template",templateId:form.get("templateId"),eventName:form.get("eventName"),eventAt:Math.floor(new Date(String(form.get("eventAt"))).getTime()/1000),attendeeCount:Number(form.get("attendeeCount"))}))event.currentTarget.reset()}
  async function proposeMaster(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(await act({action:"master_propose",entityType:form.get("entityType"),recordKey:form.get("recordKey"),reason:form.get("reason"),payload:{name:form.get("name")},effectiveFrom:Math.floor(new Date(String(form.get("effectiveFrom"))).getTime()/1000)}))event.currentTarget.reset()}
  if(!data)return <main className="p2-shell"><p>{error||"Đang tải trung tâm vận hành P2…"}</p></main>;
  const metricCost=data.analytics.costs.find(item=>item.phase==="actual")?.totalMinor??0;
  return <main className="p2-shell"><header className="p2-header"><a href="/portal"><Image src="/nic-logo.png" width={112} height={42} alt="NIC" unoptimized/></a><div><span>OPERATIONAL PORTFOLIO</span><h1>P2 Control Center</h1><p>Tài sản, chi phí, sự kiện, visitor access, master data và KPI trên cùng nguồn dữ liệu.</p></div><nav><a href="/portal/operations">Hàng đợi</a><a href="/portal/reliability">P1 Reliability</a></nav></header>
  {error&&<div className="ops-alert" role="alert">{error}<button onClick={()=>setError("")}>Đóng</button></div>}{notice&&<div className="coord-notice" role="status">{notice}</div>}
  <section className="p2-kpis"><article><span>SLA attainment</span><strong>{data.analytics.sla.attainmentPercent==null?"Chưa đủ dữ liệu":`${data.analytics.sla.attainmentPercent}%`}</strong><small>{String(data.analytics.sla.met??0)} đạt · {String(data.analytics.sla.failed??0)} vi phạm</small></article><article><span>MTTR</span><strong>{data.analytics.mttr.mttrSeconds?`${Math.round(Number(data.analytics.mttr.mttrSeconds)/3600)} giờ`:"—"}</strong><small>{String(data.analytics.mttr.resolvedCount??0)} work order đã đóng</small></article><article><span>Actual cost</span><strong>{money(metricCost)}</strong><small>Backend-calculated · price snapshot</small></article><article><span>Data quality</span><strong>{Object.values(data.analytics.quality??{}).reduce((sum,value)=>sum+Number(value??0),0)===0?"Đạt":"Cần kiểm tra"}</strong><small>Cập nhật {when(data.analytics.refreshedAt)} · {data.analytics.timezone}</small></article></section>
  <nav className="p2-tabs" aria-label="Phân hệ P2">{[["assets","Tài sản & PM"],["costs","Chi phí"],["events","Sự kiện"],["visitors","Visitor access"],["master","Master data"],["analytics","KPI & drill-down"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {tab==="assets"&&<section className="p2-layout"><article className="p2-panel"><header><span>ASSET HIERARCHY</span><h2>Danh mục tài sản</h2></header>{data.assets.map(item=><div className="p2-row" key={String(item.id)}><div><strong>{String(item.code)} · {String(item.name)}</strong><small>{String(item.parentName??"Tài sản gốc")} · {String(item.location)} · {String(item.category)}</small></div><b data-warning={item.warrantyWarning===1}>{item.warrantyWarning===1?"Sắp hết BH":String(item.status)}</b></div>)}</article><article className="p2-panel"><header><span>PREVENTIVE MAINTENANCE</span><h2>Lịch bảo trì</h2></header>{data.plans.map(item=><div className="p2-row" key={String(item.id)}><div><strong>{String(item.assetName)}</strong><small>{String(item.name)} · mỗi {String(item.recurrenceDays)} ngày · hạn {when(item.nextDueAt)}</small></div><button disabled={busy} onClick={()=>void act({action:"maintenance_generate",planId:item.id})}>{item.dueWarning===1?"Sinh work order":"Chuẩn bị"}</button></div>)}</article>{data.permissions["asset:manage"]&&<form className="p2-panel p2-form" onSubmit={createAsset}><header><span>NEW ASSET</span><h2>Thêm tài sản</h2></header><div><label>Mã<input name="code" required/></label><label>Tên<input name="name" required/></label></div><div><label>Vị trí<input name="location" required/></label><label>Danh mục<input name="category" required/></label></div><label>Thuộc tài sản<select name="parentAssetId"><option value="">Tài sản gốc</option>{data.assets.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.code)} · {String(item.name)}</option>)}</select></label><div><label>Serial<input name="serialNumber"/></label><label>Model<input name="model"/></label></div><label>Hết hạn bảo hành<input name="warrantyEnd" type="datetime-local"/></label><button disabled={busy}>Lưu tài sản</button></form>}</section>}
  {tab==="costs"&&<section className="p2-layout"><article className="p2-panel p2-wide"><header><span>WORK ORDER COST</span><h2>Estimate và actual</h2></header>{data.costs.length?data.costs.map(item=><div className="p2-row" key={`${String(item.workOrderId)}-${String(item.phase)}`}><div><strong>{String(item.workOrderId)}</strong><small>{String(item.lineCount)} dòng · {String(item.phase)} · snapshot giá bất biến</small></div><b>{money(item.totalMinor,String(item.currency))}</b></div>):<p>Chưa có dòng chi phí. API chỉ nhận quantity và đơn giá; backend tự tính thuế, giảm giá và tổng.</p>}</article><article className="p2-panel"><header><span>PROVIDER SCORECARD</span><h2>Hiệu suất nhà cung cấp</h2></header>{data.analytics.providers.map(item=><div className="p2-row" key={String(item.providerId)}><div><strong>{String(item.name)}</strong><small>{String(item.assignments)} assignment · {String(item.onTime)} đúng hạn</small></div><b>{String(item.accepted)} accepted</b></div>)}</article></section>}
  {tab==="events"&&<section className="p2-layout"><article className="p2-panel"><header><span>EVENT TEMPLATE</span><h2>Template đang quản trị</h2></header>{data.eventTemplates.map(item=><div className="p2-row" key={String(item.id)}><div><strong>{String(item.name)} · v{String(item.version)}</strong><small>{String(item.eventType)} / {String(item.scale)} · {String(item.taskCount)} task · {String(item.lineCount)} line</small></div><b>{String(item.status)}</b></div>)}</article><form className="p2-panel p2-form" onSubmit={createEvent}><header><span>CREATE FROM TEMPLATE</span><h2>Khởi tạo sự kiện</h2></header><label>Template<select name="templateId" required>{data.eventTemplates.filter(item=>item.status==="active").map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Tên sự kiện<input name="eventName" required/></label><div><label>Thời gian<input name="eventAt" type="datetime-local" required/></label><label>Số người<input name="attendeeCount" type="number" min="1" required/></label></div><button disabled={busy}>Tạo event plan</button></form><article className="p2-panel p2-wide"><header><span>CHECKLIST & BUDGET</span><h2>Điều phối đang chạy</h2></header>{data.events.map(item=><div className="p2-event" key={String(item.id)}><div className="p2-row"><div><strong>{String(item.eventName)}</strong><small>{when(item.eventAt)} · {String(item.templateName??"Không template")}</small></div><b>{money(item.budgetEstimateMinor)} · {String(item.budgetStatus)}</b></div>{data.eventTasks.filter(task=>task.eventOrderId===item.id).map(task=><div className="p2-task" key={String(task.id)}><span>{String(task.sequence)}. {String(task.title)}</span><small>{when(task.dueAt)}</small>{task.status!=="completed"&&<button disabled={busy||Boolean(task.dependencyStatus&&task.dependencyStatus!=="completed")} onClick={()=>void act({action:"event_task_complete",id:task.id})}>Hoàn thành</button>}<b>{String(task.status)}</b></div>)}</div>)}</article></section>}
  {tab==="visitors"&&<section className="p2-layout"><article className="p2-panel p2-wide"><header><span>KIOSK · QR · BADGE · ACCESS</span><h2>Hành trình khách tại sảnh</h2></header>{data.visitors.map(item=><div className="p2-row p2-visitor" key={String(item.id)}><div><strong>{String(item.visitorName)} · {String(item.organization)}</strong><small>{when(item.visitAt)} · {String(item.accessZone??"Chưa gán zone")} · {String(item.grantStatus??"Chưa cấp quyền")}</small></div><b>{String(item.status)}</b><div>{item.status==="approved"&&<><button disabled={busy||!data.zones[0]} onClick={()=>void act({action:"visitor_qr_issue",visitorId:item.id,zoneId:data.zones[0]?.id,ttlMinutes:60})}>Phát QR</button><button disabled={busy} onClick={()=>void act({action:"visitor_offline_hold",visitorId:item.id,reason:"Controller hoặc kiosk offline; chờ Security xác minh thủ công"})}>Offline hold</button></>}{["approved","checked_in"].includes(String(item.status))&&<button disabled={busy} onClick={()=>void act({action:"badge_print",visitorId:item.id,printerRef:"reception-printer-01",reason:item.status==="checked_in"?"In lại theo yêu cầu tại quầy":""})}>In badge</button>}{item.status==="checked_in"&&<button disabled={busy} onClick={()=>void act({action:"visitor_checkout",visitorId:item.id})}>Check-out</button>}</div></div>)}</article><article className="p2-panel"><header><span>PRINT AUDIT</span><h2>Lịch sử in badge</h2></header>{data.badgeJobs.map(item=><div className="p2-row" key={String(item.id)}><div><strong>{String(item.visitorName)}</strong><small>{String(item.printerRef)} · {when(item.createdAt)}</small></div><b>{item.isReprint===1?"Reprint":"First print"}</b></div>)}</article></section>}
  {tab==="master"&&<section className="p2-layout"><article className="p2-panel"><header><span>EFFECTIVE-DATED MASTER DATA</span><h2>Phiên bản dữ liệu chuẩn</h2></header>{data.masterRecords.map(item=><div className="p2-row" key={String(item.id)}><div><strong>{String(item.entityType)} · {String(item.recordKey)} · v{String(item.version)}</strong><small>Hiệu lực {when(item.effectiveFrom)} · {String(item.reason)}</small></div><b>{String(item.status)}</b></div>)}</article>{data.permissions["master_data:manage"]&&<form className="p2-panel p2-form" onSubmit={proposeMaster}><header><span>MAKER-CHECKER</span><h2>Đề xuất thay đổi</h2></header><label>Loại<select name="entityType"><option value="asset_category">Asset category</option><option value="cost_catalog">Cost catalog</option><option value="provider">Provider</option><option value="access_zone">Access zone</option><option value="event_catalog">Event catalog</option></select></label><div><label>Key<input name="recordKey" required/></label><label>Tên<input name="name" required/></label></div><label>Hiệu lực từ<input name="effectiveFrom" type="datetime-local" required/></label><label>Lý do<textarea name="reason" required/></label><button disabled={busy}>Tạo bản nháp</button></form>}</section>}
  {tab==="analytics"&&<section className="p2-layout"><article className="p2-panel p2-wide"><header><span>AUTHORIZED DRILL-DOWN</span><h2>Nguồn dữ liệu KPI</h2></header>{data.analytics.drilldown.map(item=><div className="p2-row" key={String(item.id)}><div><strong>{String(item.title)}</strong><small>{String(item.location)} · {String(item.providerName??"Nội bộ")} · {String(item.assetName??"Không gắn asset")} · {when(item.updatedAt)}</small></div><b>{money(item.costMinor)}</b></div>)}</article></section>}
  </main>
}
