"use client";
import Image from "next/image";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Item=Record<string,unknown>;
type Data={role:string;permissions:{manage:boolean;approve:boolean;receive:boolean;invoice:boolean};providers:Item[];workOrders:Item[];events:Item[];contracts:Item[];purchaseOrders:Item[];purchaseOrderLines:Item[];approvals:Item[];receipts:Item[];invoices:Item[];matches:Item[];exceptions:Item[];policy?:Item};
const csrf=()=>({"content-type":"application/json","x-csrf-token":decodeURIComponent(document.cookie.split("; ").find(value=>value.startsWith("nic_csrf="))?.split("=").slice(1).join("=")??"")});
const money=(value:unknown,currency="VND")=>new Intl.NumberFormat("vi-VN",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value??0));
const parseLines=(value:string)=>value.split("\n").map(line=>line.trim()).filter(Boolean).map(line=>{const [description,lineType="service",quantity="1000",unit="gói",price="0"]=line.split("|").map(v=>v.trim());return{description,lineType,quantityMilli:Number(quantity),unit,unitPriceMinor:Number(price)}});

export function ProcurementCenter(){
  const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch("/api/procurement");if(response.status===401){location.href="/auth";return}const body=await response.json();if(!response.ok)throw new Error(body.error??"Không tải được procurement");setData(body)},[]);
  useEffect(()=>{fetch("/api/procurement").then(async response=>{if(response.status===401){location.href="/auth";return null}const body=await response.json();if(!response.ok)throw new Error(body.error??"Không tải được procurement");return body}).then(body=>{if(body)setData(body)}).catch(reason=>setError(String(reason)))},[]);
  async function act(payload:Item,idempotency=false){setBusy(true);setError("");const headers:Record<string,string>=csrf();if(idempotency)headers["idempotency-key"]=`ui-${crypto.randomUUID()}`;const response=await fetch("/api/procurement",{method:"POST",headers,body:JSON.stringify(payload)}),body=await response.json();setBusy(false);if(!response.ok){setError(body.error??"Không thể thực hiện");return false}setNotice("Đã cập nhật chứng từ và audit trail.");await load();return true}
  async function createPo(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),target=String(form.get("target")??""),[kind,id]=target.split(":");if(await act({action:"po_create",poNumber:form.get("poNumber"),providerId:form.get("providerId"),contractId:form.get("contractId")||null,workOrderId:kind==="wo"?id:null,eventOrderId:kind==="event"?id:null,currency:"VND",lines:parseLines(String(form.get("lines")??""))},true))event.currentTarget.reset()}
  async function createContract(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),now=Math.floor(Date.now()/1000);if(await act({action:"contract_create",contractNumber:form.get("contractNumber"),title:form.get("title"),providerId:form.get("providerId"),currency:"VND",validFrom:now,validUntil:now+365*86400,ceilingMinor:Number(form.get("ceilingMinor")),lines:parseLines(String(form.get("lines")??"")).map(line=>({...line,maxQuantityMilli:line.quantityMilli}))}))event.currentTarget.reset()}
  async function createInvoice(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),lineId=String(form.get("lineId")??""),line=data?.purchaseOrderLines.find(value=>value.id===lineId);if(!line)return;if(await act({action:"invoice_create",purchaseOrderId:line.purchaseOrderId,invoiceNumber:form.get("invoiceNumber"),invoiceDate:Math.floor(Date.now()/1000),lines:[{purchaseOrderLineId:line.id,quantityMilli:Number(form.get("quantityMilli")),unitPriceMinor:Number(form.get("unitPriceMinor"))}]},true))event.currentTarget.reset()}
  if(!data)return <main className="proc-shell"><p>{error||"Đang tải trung tâm procurement…"}</p></main>;
  const lineFor=(poId:unknown)=>data.purchaseOrderLines.filter(line=>line.purchaseOrderId===poId),pending=data.approvals.filter(value=>value.status==="pending");
  return <main className="proc-shell">
    <header className="proc-header"><a href="/portal"><Image src="/nic-logo.png" width={110} height={40} alt="NIC" unoptimized/></a><div><span>PROCURE-TO-PAY CONTROL</span><h1>Hợp đồng & mua sắm</h1><p>PO, thực nhận, hóa đơn và đối chiếu ba bên có kiểm soát.</p></div><nav><a href="/portal/portfolio">Danh mục P2</a><a href="/portal/reliability">Độ tin cậy</a></nav></header>
    {error&&<div className="proc-alert">{error}<button onClick={()=>setError("")}>Đóng</button></div>}{notice&&<div className="proc-notice">{notice}</div>}
    <section className="proc-kpis"><article><span>Ngưỡng duyệt PO</span><strong>{money(data.policy?.poApprovalThresholdMinor)}</strong><small>Policy theo organization</small></article><article><span>PO đang mở</span><strong>{data.purchaseOrders.filter(po=>!["closed","cancelled"].includes(String(po.status))).length}</strong><small>{pending.length} chờ duyệt</small></article><article><span>Invoice exception</span><strong>{data.exceptions.filter(value=>value.status==="open").length}</strong><small>Tạo incident tự động</small></article><article><span>Tolerance giá</span><strong>{Number(data.policy?.priceToleranceBps??0)/100}%</strong><small>Three-way match</small></article></section>
    <section className="proc-grid">
      {data.permissions.manage&&<form className="proc-panel proc-form" onSubmit={createContract}><header><span>CONTRACT</span><h2>Tạo phiên bản hợp đồng</h2></header><label>Số hợp đồng<input name="contractNumber" required/></label><label>Tiêu đề<input name="title" required/></label><label>Provider<select name="providerId" required><option value="">Chọn provider</option>{data.providers.map(provider=><option key={String(provider.id)} value={String(provider.id)}>{String(provider.name)}</option>)}</select></label><label>Trần hợp đồng (VND)<input name="ceilingMinor" type="number" min="0" required/></label><label>Dòng hợp đồng<textarea name="lines" required defaultValue="Bảo trì thiết bị|service|12000|giờ|350000"/><small>Mô tả | loại | số lượng milli | đơn vị | đơn giá</small></label><button disabled={busy}>Kích hoạt hợp đồng</button></form>}
      {data.permissions.manage&&<form className="proc-panel proc-form" onSubmit={createPo}><header><span>PURCHASE ORDER</span><h2>Tạo PO</h2></header><label>Số PO<input name="poNumber" required/></label><label>Provider<select name="providerId" required><option value="">Chọn provider</option>{data.providers.map(provider=><option key={String(provider.id)} value={String(provider.id)}>{String(provider.name)}</option>)}</select></label><label>Hợp đồng<select name="contractId"><option value="">Không liên kết</option>{data.contracts.filter(value=>value.status==="active").map(value=><option key={String(value.id)} value={String(value.id)}>{String(value.contractNumber)} · v{String(value.version)}</option>)}</select></label><label>Nhu cầu vận hành<select name="target" required><option value="">Chọn work order/event</option>{data.workOrders.map(value=><option key={String(value.id)} value={`wo:${String(value.id)}`}>WO · {String(value.title)}</option>)}{data.events.map(value=><option key={String(value.id)} value={`event:${String(value.id)}`}>Event · {String(value.eventName)}</option>)}</select></label><label>Dòng PO<textarea name="lines" required defaultValue="Vật tư bảo trì|material|1000|bộ|12000000"/><small>Mô tả | loại | số lượng milli | đơn vị | đơn giá</small></label><button disabled={busy}>Tạo PO</button></form>}
      <article className="proc-panel proc-wide"><header><span>ORDER LEDGER</span><h2>Purchase orders</h2></header>{data.purchaseOrders.length?data.purchaseOrders.map(po=><div className="proc-document" key={String(po.id)}><div><strong>{String(po.poNumber)} · {String(po.providerName)}</strong><small>{money(po.subtotalMinor,String(po.currency))} · {lineFor(po.id).length} dòng</small></div><b data-state={String(po.status)}>{String(po.status)}</b><div className="proc-actions">{data.permissions.approve&&pending.filter(value=>value.purchaseOrderId===po.id).map(value=><span key={String(value.id)}><button disabled={busy||value.requestedBy===undefined} onClick={()=>void act({action:"po_decide",approvalId:value.id,decision:"approved",note:"Đạt policy procurement"})}>Duyệt</button><button disabled={busy} onClick={()=>void act({action:"po_decide",approvalId:value.id,decision:"rejected",note:"Không đạt policy"})}>Từ chối</button></span>)}{data.permissions.manage&&po.status==="approved"&&<button disabled={busy} onClick={()=>void act({action:"po_issue",id:po.id})}>Phát hành</button>}{data.permissions.receive&&["issued","partially_received"].includes(String(po.status))&&<button disabled={busy} onClick={()=>{const lines=lineFor(po.id),line=lines.find(value=>Number(value.receivedMilli)<Number(value.quantityMilli));if(line)void act({action:"receipt_create",purchaseOrderId:po.id,receiptNumber:`GR-${Date.now()}`,receivedAt:Math.floor(Date.now()/1000),lines:[{purchaseOrderLineId:line.id,quantityReceivedMilli:Number(line.quantityMilli)-Number(line.receivedMilli),condition:"accepted",note:"Nhận qua portal"}]},true)}}>Ghi nhận đủ dòng kế</button>}</div></div>):<p>Chưa có PO.</p>}</article>
      <article className="proc-panel"><header><span>RECEIPTS</span><h2>Thực nhận</h2></header>{data.receipts.map(value=><div className="proc-row" key={String(value.id)}><div><strong>{String(value.receiptNumber)}</strong><small>{String(value.lineCount)} dòng · {String(value.quantityMilli)} milli</small></div><b>{String(value.status)}</b></div>)}</article>
      {data.permissions.invoice&&<form className="proc-panel proc-form" onSubmit={createInvoice}><header><span>SUPPLIER INVOICE</span><h2>Ghi nhận hóa đơn</h2></header><label>Số hóa đơn<input name="invoiceNumber" required/></label><label>Dòng PO đã nhận<select name="lineId" required><option value="">Chọn dòng</option>{data.purchaseOrderLines.filter(line=>Number(line.receivedMilli)>0).map(line=><option key={String(line.id)} value={String(line.id)}>{String(line.description)} · đã nhận {String(line.receivedMilli)}</option>)}</select></label><label>Số lượng milli<input name="quantityMilli" type="number" min="1" required/></label><label>Đơn giá thực tế<input name="unitPriceMinor" type="number" min="0" required/></label><button disabled={busy}>Tạo invoice chờ match</button></form>}
      <article className="proc-panel"><header><span>INVOICES</span><h2>Đối chiếu hóa đơn</h2></header>{data.invoices.map(value=><div className="proc-row" key={String(value.id)}><div><strong>{String(value.invoiceNumber)} · {String(value.providerName)}</strong><small>{money(value.totalMinor,String(value.currency))}</small></div><b>{String(value.status)}</b>{data.permissions.invoice&&value.status==="pending_match"&&<button disabled={busy} onClick={()=>void act({action:"invoice_match",invoiceId:value.id})}>Three-way match</button>}</div>)}</article>
      <article className="proc-panel proc-wide"><header><span>EXCEPTION WORKFLOW</span><h2>Sai lệch cần xử lý</h2></header>{data.exceptions.length?data.exceptions.map(value=><div className="proc-row" key={String(value.id)}><div><strong>{String(value.exceptionType)}</strong><small>Invoice {String(value.invoiceId)} · {String(value.assignedRole)}</small></div><b data-state={String(value.severity)}>{String(value.status)} · {String(value.severity)}</b></div>):<p>Không có exception mở.</p>}</article>
    </section>
  </main>
}
