"use client";

import Image from "next/image";
import { useCallback, useEffect, useMemo, useState } from "react";

type RequestItem = { id:string;serviceType:string;title:string;details:string;status:string;targetDepartment:string;assignedTo:string|null;organization:string;createdAt:number;updatedAt:number|null };
type Filter = "all"|"active"|"waiting_customer"|"resolved";

const statusLabels:Record<string,string>={submitted:"Đã tiếp nhận",triaged:"Đã phân loại",in_progress:"Đang xử lý",waiting_customer:"Cần bổ sung",resolved:"Đã hoàn tất",cancelled:"Đã hủy"};
const serviceLabels:Record<string,string>={space_booking:"Không gian",support:"Hỗ trợ vận hành",event_registration:"Sự kiện",access_card:"Thẻ và quyền ra vào"};

function visibleForFilter(item:RequestItem,filter:Filter){if(filter==="all")return true;if(filter==="active")return["submitted","triaged","in_progress"].includes(item.status);return item.status===filter;}

export function RequestsPortal(){
  const[requests,setRequests]=useState<RequestItem[]>([]),[scope,setScope]=useState(""),[filter,setFilter]=useState<Filter>("all"),[selected,setSelected]=useState<RequestItem|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/requests",{headers:{Accept:"application/json"}});if(response.status===401){location.href="/auth";return;}const data=await response.json().catch(()=>({})) as {error?:string;scope?:string;requests?:RequestItem[]};if(!response.ok)throw new Error(data.error??"Không thể tải yêu cầu.");setRequests(data.requests??[]);setScope(data.scope??"");}catch{setError("Không thể tải danh sách yêu cầu. Vui lòng thử lại.");}finally{setLoading(false);}},[]);
  useEffect(()=>{let active=true;fetch("/api/requests",{headers:{Accept:"application/json"}}).then(async response=>{if(response.status===401){location.href="/auth";return;}const data=await response.json().catch(()=>({})) as {error?:string;scope?:string;requests?:RequestItem[]};if(!response.ok)throw new Error(data.error??"Không thể tải yêu cầu.");if(active){setRequests(data.requests??[]);setScope(data.scope??"");}}).catch(()=>{if(active)setError("Không thể tải danh sách yêu cầu. Vui lòng thử lại.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const filtered=useMemo(()=>requests.filter(item=>visibleForFilter(item,filter)),[requests,filter]);
  return <main className="requests-shell"><header className="requests-header"><a href="/portal"><Image src="/nic-logo.png" alt="NIC" width={128} height={48} unoptimized/><span><strong>Service Hub</strong><small>Quản lý yêu cầu</small></span></a><nav aria-label="Điều hướng yêu cầu"><a href="/portal">Trang chủ</a><a className="active" href="/portal/requests">Yêu cầu</a><a href="/portal/bookings">Đặt chỗ</a><a href="/portal/coordination">Khách và sự kiện</a></nav><a className="requests-create" href="/portal">Tạo yêu cầu</a></header>
    <section className="requests-main"><header className="requests-title"><div><span>YÊU CẦU DỊCH VỤ</span><h1>Theo dõi mọi yêu cầu.</h1><p>Dữ liệu được giới hạn theo quyền tài khoản và phạm vi tổ chức của bạn.</p></div><button onClick={()=>void load()} disabled={loading}>{loading?"Đang tải...":"Làm mới"}</button></header>
      <div className="requests-toolbar" role="group" aria-label="Lọc yêu cầu">{([["all","Tất cả"],["active","Đang xử lý"],["waiting_customer","Cần bổ sung"],["resolved","Đã hoàn tất"]] as Array<[Filter,string]>).map(([value,label])=><button key={value} className={filter===value?"active":""} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}<span>{scope==="organization"?"Phạm vi doanh nghiệp":scope==="assigned_team"?"Phạm vi đội phụ trách":"Yêu cầu của tôi"}</span></div>
      {error?<section className="requests-state error" role="alert"><strong>Chưa tải được dữ liệu</strong><p>{error}</p><button onClick={()=>void load()}>Thử lại</button></section>:loading?<section className="requests-loading" aria-label="Đang tải yêu cầu"><i/><i/><i/></section>:filtered.length===0?<section className="requests-state"><strong>Không có yêu cầu phù hợp</strong><p>Đổi bộ lọc hoặc tạo yêu cầu mới từ trang chủ.</p><a href="/portal">Tạo yêu cầu</a></section>:<section className="requests-list" aria-label="Danh sách yêu cầu">{filtered.map(item=><article key={item.id}><div className="request-identity"><span>{serviceLabels[item.serviceType]??item.serviceType}</span><strong>{item.title}</strong><small>{item.id}</small></div><div><span>Đội xử lý</span><strong>{item.targetDepartment}</strong></div><div><span>Cập nhật</span><time>{new Date((item.updatedAt??item.createdAt)*1000).toLocaleString("vi-VN")}</time></div><b data-status={item.status}>{statusLabels[item.status]??item.status}</b><button onClick={()=>setSelected(item)}>Xem chi tiết</button></article>)}</section>}
    </section>
    {selected&&<div className="request-detail-layer" onMouseDown={event=>event.target===event.currentTarget&&setSelected(null)}><section className="request-detail" role="dialog" aria-modal="true" aria-labelledby="request-detail-title"><header><div><span>{selected.id}</span><h2 id="request-detail-title">{selected.title}</h2></div><button onClick={()=>setSelected(null)} aria-label="Đóng chi tiết">×</button></header><dl><div><dt>Trạng thái</dt><dd><b data-status={selected.status}>{statusLabels[selected.status]??selected.status}</b></dd></div><div><dt>Dịch vụ</dt><dd>{serviceLabels[selected.serviceType]??selected.serviceType}</dd></div><div><dt>Đội xử lý</dt><dd>{selected.targetDepartment}</dd></div><div><dt>Doanh nghiệp</dt><dd>{selected.organization}</dd></div><div><dt>Ngày tạo</dt><dd>{new Date(selected.createdAt*1000).toLocaleString("vi-VN")}</dd></div><div><dt>Phụ trách</dt><dd>{selected.assignedTo??"Chưa phân công"}</dd></div></dl><section><h3>Thông tin đã gửi</h3><p>{selected.details}</p></section><footer><button onClick={()=>setSelected(null)}>Đóng</button><a href="/portal">Tạo yêu cầu khác</a></footer></section></div>}
  </main>;
}
