"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";

type RequestItem = { id:string;serviceType:string;title:string;details:string;status:string;targetDepartment:string;assignedTo:string|null;organization:string;createdAt:number;updatedAt:number|null };
type CommentItem = { id:string;authorId:string;authorName:string;authorRole:string;body:string;createdAt:number };
type TimelineItem = { id:string;action:string;actorName:string;metadata:Record<string,unknown>;createdAt:number };
type RequestDetail = { request:RequestItem;comments:CommentItem[];timeline:TimelineItem[];permissions:{canComment:boolean;canCancel:boolean} };
type Filter = "all"|"active"|"waiting_customer"|"resolved";

const statusLabels:Record<string,string>={submitted:"Đã tiếp nhận",triaged:"Đã phân loại",in_progress:"Đang xử lý",waiting_customer:"Cần bổ sung",resolved:"Đã hoàn tất",cancelled:"Đã hủy"};
const serviceLabels:Record<string,string>={space_booking:"Không gian",support:"Hỗ trợ vận hành",event_registration:"Sự kiện",access_card:"Thẻ và quyền ra vào"};
const timelineLabels:Record<string,string>={"request.submitted":"Yêu cầu đã được gửi","request.operated":"Cập nhật xử lý","request.comment_added":"Đã thêm trao đổi","request.cancelled_by_customer":"Khách hàng đã hủy yêu cầu"};

function visibleForFilter(item:RequestItem,filter:Filter){if(filter==="all")return true;if(filter==="active")return["submitted","triaged","in_progress"].includes(item.status);return item.status===filter;}
function csrfHeaders(){const token=document.cookie.split(";").map(value=>value.trim()).find(value=>value.startsWith("nic_csrf="))?.slice(9)??"";return{"Content-Type":"application/json","X-CSRF-Token":decodeURIComponent(token)};}
function requestError(code?:string){return({COMMENT_INVALID:"Nội dung trao đổi phải có từ 1 đến 2.000 ký tự.",REQUEST_CLOSED:"Yêu cầu đã đóng nên không thể thêm trao đổi.",CANCELLATION_NOT_ALLOWED:"Yêu cầu đã bắt đầu thực hiện nên không thể tự hủy.",REQUEST_CHANGED:"Yêu cầu vừa được cập nhật. Hãy tải lại và thử lại.",RATE_LIMITED:"Bạn thao tác quá nhanh. Vui lòng thử lại sau."} as Record<string,string>)[code??""]??"Không thể hoàn tất thao tác. Vui lòng thử lại.";}

export function RequestsPortal(){
  const[requests,setRequests]=useState<RequestItem[]>([]),[scope,setScope]=useState(""),[filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState<RequestDetail|null>(null),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState(""),[actionPending,setActionPending]=useState(false);

  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/requests",{headers:{Accept:"application/json"}});if(response.status===401){location.href="/auth";return;}const data=await response.json().catch(()=>({})) as {error?:string;scope?:string;requests?:RequestItem[]};if(!response.ok)throw new Error(data.error??"LOAD_FAILED");setRequests(data.requests??[]);setScope(data.scope??"");}catch{setError("Không thể tải danh sách yêu cầu. Vui lòng thử lại.");}finally{setLoading(false);}},[]);
  const loadDetail=useCallback(async(id:string)=>{setSelectedId(id);setDetail(null);setDetailError("");setDetailLoading(true);try{const response=await fetch(`/api/requests/${encodeURIComponent(id)}`,{headers:{Accept:"application/json"}});if(response.status===401){location.href="/auth";return;}const data=await response.json().catch(()=>({})) as RequestDetail&{error?:string};if(!response.ok)throw new Error(data.error??"LOAD_FAILED");setDetail(data);}catch{setDetailError("Không thể tải chi tiết hoặc bạn không còn quyền xem yêu cầu này.");}finally{setDetailLoading(false);}},[]);
  const openRequest=useCallback((id:string)=>{const url=new URL(location.href);url.searchParams.set("request",id);history.replaceState({},"",url);void loadDetail(id);},[loadDetail]);
  const closeDetail=useCallback(()=>{setSelectedId(null);setDetail(null);setDetailError("");const url=new URL(location.href);url.searchParams.delete("request");history.replaceState({},"",url);},[]);

  useEffect(()=>{const timer=window.setTimeout(()=>{void load();const requestId=new URLSearchParams(location.search).get("request");if(requestId)void loadDetail(requestId);},0);return()=>window.clearTimeout(timer);},[load,loadDetail]);
  const filtered=useMemo(()=>{const normalized=query.trim().toLocaleLowerCase("vi");return requests.filter(item=>visibleForFilter(item,filter)&&(!normalized||`${item.title} ${item.id} ${item.targetDepartment}`.toLocaleLowerCase("vi").includes(normalized)));},[requests,filter,query]);

  async function addComment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail||actionPending)return;const form=event.currentTarget;const formData=new FormData(form);const body=String(formData.get("comment")??"").trim();setActionPending(true);setDetailError("");try{const response=await fetch(`/api/requests/${encodeURIComponent(detail.request.id)}`,{method:"POST",headers:csrfHeaders(),body:JSON.stringify({action:"comment",body})});const data=await response.json().catch(()=>({})) as {error?:string};if(!response.ok)throw new Error(data.error??"ACTION_FAILED");form.reset();await loadDetail(detail.request.id);}catch(cause){setDetailError(requestError(cause instanceof Error?cause.message:undefined));}finally{setActionPending(false);}}
  async function cancelRequest(){if(!detail||actionPending||!confirm("Hủy yêu cầu này? Hành động sẽ được ghi vào lịch sử xử lý."))return;setActionPending(true);setDetailError("");try{const response=await fetch(`/api/requests/${encodeURIComponent(detail.request.id)}`,{method:"POST",headers:csrfHeaders(),body:JSON.stringify({action:"cancel"})});const data=await response.json().catch(()=>({})) as {error?:string};if(!response.ok)throw new Error(data.error??"ACTION_FAILED");await Promise.all([load(),loadDetail(detail.request.id)]);}catch(cause){setDetailError(requestError(cause instanceof Error?cause.message:undefined));}finally{setActionPending(false);}}

  return <main className="requests-shell"><section className="requests-main"><header className="requests-title"><div><span>YÊU CẦU DỊCH VỤ</span><h1>Theo dõi mọi yêu cầu.</h1><p>Dữ liệu, trao đổi và dòng thời gian được giới hạn theo quyền tài khoản của bạn.</p></div><button onClick={()=>void load()} disabled={loading}>{loading?"Đang tải...":"Làm mới"}</button></header>
    <div className="requests-controls"><div className="requests-toolbar" role="group" aria-label="Lọc yêu cầu">{([["all","Tất cả"],["active","Đang xử lý"],["waiting_customer","Cần bổ sung"],["resolved","Đã hoàn tất"]] as Array<[Filter,string]>).map(([value,label])=><button key={value} className={filter===value?"active":""} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}<span>{scope==="organization"?"Phạm vi doanh nghiệp":scope==="assigned_team"?"Phạm vi đội phụ trách":"Yêu cầu của tôi"}</span></div><label className="requests-search"><span>Tìm yêu cầu</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Mã, tiêu đề hoặc đội xử lý"/></label></div>
    {error?<section className="requests-state error" role="alert"><strong>Chưa tải được dữ liệu</strong><p>{error}</p><button onClick={()=>void load()}>Thử lại</button></section>:loading?<section className="requests-loading" aria-label="Đang tải yêu cầu"><i/><i/><i/></section>:filtered.length===0?<section className="requests-state"><strong>Không có yêu cầu phù hợp</strong><p>Đổi bộ lọc, từ khóa hoặc tạo yêu cầu mới từ trang chủ.</p><a href="/portal">Tạo yêu cầu</a></section>:<section className="requests-list" aria-label="Danh sách yêu cầu">{filtered.map(item=><article key={item.id}><div className="request-identity"><span>{serviceLabels[item.serviceType]??item.serviceType}</span><strong>{item.title}</strong><small>{item.id}</small></div><div><span>Đội xử lý</span><strong>{item.targetDepartment}</strong></div><div><span>Cập nhật</span><time>{new Date((item.updatedAt??item.createdAt)*1000).toLocaleString("vi-VN")}</time></div><b data-status={item.status}>{statusLabels[item.status]??item.status}</b><button onClick={()=>openRequest(item.id)}>Xem chi tiết</button></article>)}</section>}
  </section>
  {selectedId&&<div className="request-detail-layer" onMouseDown={event=>event.target===event.currentTarget&&closeDetail()}><section className="request-detail" role="dialog" aria-modal="true" aria-labelledby="request-detail-title"><header><div><span>{selectedId}</span><h2 id="request-detail-title">{detail?.request.title??"Chi tiết yêu cầu"}</h2></div><button onClick={closeDetail} aria-label="Đóng chi tiết">×</button></header>
    {detailLoading?<div className="request-detail-state">Đang tải chi tiết…</div>:detailError&&!detail?<div className="request-detail-state error"><p>{detailError}</p><button onClick={()=>void loadDetail(selectedId)}>Thử lại</button></div>:detail&&<><dl><div><dt>Trạng thái</dt><dd><b data-status={detail.request.status}>{statusLabels[detail.request.status]??detail.request.status}</b></dd></div><div><dt>Dịch vụ</dt><dd>{serviceLabels[detail.request.serviceType]??detail.request.serviceType}</dd></div><div><dt>Đội xử lý</dt><dd>{detail.request.targetDepartment}</dd></div><div><dt>Doanh nghiệp</dt><dd>{detail.request.organization}</dd></div><div><dt>Ngày tạo</dt><dd>{new Date(detail.request.createdAt*1000).toLocaleString("vi-VN")}</dd></div><div><dt>Phụ trách</dt><dd>{detail.request.assignedTo??"Chưa phân công"}</dd></div></dl>
      <section className="request-submitted"><h3>Thông tin đã gửi</h3><p>{detail.request.details}</p></section>
      <div className="request-collaboration"><section className="request-thread"><header><h3>Trao đổi</h3><span>{detail.comments.length} phản hồi</span></header>{detail.comments.length?<div className="request-comments">{detail.comments.map(comment=><article key={comment.id}><header><strong>{comment.authorName}</strong><time>{new Date(comment.createdAt*1000).toLocaleString("vi-VN")}</time></header><p>{comment.body}</p></article>)}</div>:<p className="request-empty">Chưa có trao đổi nào.</p>}{detail.permissions.canComment&&<form onSubmit={event=>void addComment(event)}><label htmlFor="request-comment">Thêm nội dung trao đổi</label><textarea id="request-comment" name="comment" minLength={1} maxLength={2000} required placeholder="Bổ sung thông tin hoặc phản hồi đội xử lý…"/><button disabled={actionPending}>{actionPending?"Đang gửi…":"Gửi phản hồi"}</button></form>}</section>
        <section className="request-timeline"><h3>Dòng thời gian</h3>{detail.timeline.length?<ol>{detail.timeline.map(entry=><li key={entry.id}><i/><div><strong>{timelineLabels[entry.action]??entry.action}</strong><span>{entry.actorName}</span><time>{new Date(entry.createdAt*1000).toLocaleString("vi-VN")}</time></div></li>)}</ol>:<p className="request-empty">Chưa có sự kiện được ghi nhận.</p>}</section></div>
      {detailError&&<p className="request-action-error" role="alert">{detailError}</p>}
      <footer>{detail.permissions.canCancel&&<button className="request-cancel" onClick={()=>void cancelRequest()} disabled={actionPending}>Hủy yêu cầu</button>}<button onClick={closeDetail}>Đóng</button><a href="/portal">Tạo yêu cầu khác</a></footer></>}
  </section></div>}
  </main>;
}
