-- Generated by scripts/generate-postgres-migration.mjs.
-- The application owns an isolated schema so it cannot collide with the legacy
-- public Supabase/RLS prototype.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS nic_app;
REVOKE ALL ON SCHEMA nic_app FROM PUBLIC, anon, authenticated;
SET LOCAL search_path = nic_app, public;

CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"full_name" text NOT NULL,
	"organization" text NOT NULL,
	"role" text DEFAULT 'tenant_member' NOT NULL,
	"password_hash" text NOT NULL,
	"password_salt" text NOT NULL,
	"password_iterations" integer DEFAULT 210000 NOT NULL,
	"failed_attempts" integer DEFAULT 0 NOT NULL,
	"locked_until" integer,
	"created_at" integer NOT NULL
);

CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");

CREATE TABLE "service_drafts" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_id" text NOT NULL,
	"service_type" text NOT NULL,
	"title" text NOT NULL,
	"details" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"confirmed_version" integer,
	"created_at" integer NOT NULL,
	"updated_at" integer NOT NULL,
	FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE cascade
);

CREATE TABLE "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" integer NOT NULL,
	"created_at" integer NOT NULL,
	FOREIGN KEY ("user_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE cascade
);

CREATE UNIQUE INDEX "sessions_token_hash_unique" ON "sessions" ("token_hash");

CREATE INDEX "sessions_user_id_idx" ON "sessions" ("user_id");

CREATE INDEX "service_drafts_owner_updated_idx" ON "service_drafts" ("owner_id", "updated_at");

INSERT INTO "users" ("id","email","full_name","organization","role","password_hash","password_salt","password_iterations","failed_attempts","created_at") VALUES ('demo-tenant-001','thanh@demo.nic.vn','Nguyễn Thanh','Innovate Vietnam','tenant_member','HRmOebKvkWNFHk/nYtVLHbblPFDG01IwS09B/PZq7RM=','UZ9cM6ihl20HzLKw7olQqA==',210000,0,1784552400);

CREATE TABLE "audit_logs" (
	"id" text PRIMARY KEY NOT NULL,
	"actor_id" text NOT NULL,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"metadata" text DEFAULT '{}' NOT NULL,
	"created_at" integer NOT NULL,
	FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action
);

CREATE TABLE "service_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"draft_id" text NOT NULL,
	"owner_id" text NOT NULL,
	"organization" text NOT NULL,
	"service_type" text NOT NULL,
	"title" text NOT NULL,
	"details" text NOT NULL,
	"status" text DEFAULT 'submitted' NOT NULL,
	"idempotency_key" text NOT NULL,
	"created_at" integer NOT NULL,
	FOREIGN KEY ("draft_id") REFERENCES "service_drafts"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action
);

CREATE UNIQUE INDEX "service_requests_draft_id_unique" ON "service_requests" ("draft_id");

CREATE UNIQUE INDEX "service_requests_owner_idempotency_idx" ON "service_requests" ("owner_id","idempotency_key");

CREATE TABLE "rate_limits" (
	"bucket_key" text PRIMARY KEY NOT NULL,
	"window_start" integer NOT NULL,
	"count" integer DEFAULT 1 NOT NULL,
	"expires_at" integer NOT NULL
);

ALTER TABLE "sessions" ADD "csrf_hash" text NOT NULL DEFAULT '';

CREATE TABLE "departments" (
  "id" text PRIMARY KEY NOT NULL,
  "organization" text NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "accepts_requests" integer DEFAULT 1 NOT NULL
);

CREATE UNIQUE INDEX "departments_org_code_unique" ON "departments" ("organization","code");

CREATE TABLE "organization_memberships" (
  "id" text PRIMARY KEY NOT NULL,
  "user_id" text NOT NULL,
  "organization" text NOT NULL,
  "department_id" text,
  "role" text DEFAULT 'customer_member' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE cascade,
  FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON UPDATE no action ON DELETE no action
);

CREATE UNIQUE INDEX "memberships_user_org_unique" ON "organization_memberships" ("user_id","organization");

ALTER TABLE "service_requests" ADD "target_department" text DEFAULT 'service_desk' NOT NULL;

ALTER TABLE "service_requests" ADD "requester_role" text DEFAULT 'customer_member' NOT NULL;

ALTER TABLE "service_requests" ADD "assigned_to" text REFERENCES users(id);

ALTER TABLE "service_requests" ADD "visibility" text DEFAULT 'organization' NOT NULL;

INSERT INTO "departments" ("id","organization","code","name","accepts_requests") VALUES
  ('nic-team-service-desk','NIC','service_desk','Service Desk',1),
  ('nic-team-facility','NIC','facility','Facility Operations',1),
  ('nic-team-event','NIC','event','Event Operations',1),
  ('nic-team-security','NIC','security','Security & Visitor Services',1),
  ('demo-customer-team','Innovate Vietnam','customer','Customer Team',0);

INSERT INTO "organization_memberships" ("id","user_id","organization","department_id","role","status","created_at")
SELECT 'demo-membership-001', id, organization, 'demo-customer-team', 'customer_admin', 'active', created_at FROM users WHERE email = 'thanh@demo.nic.vn';

CREATE TABLE "spaces" (
  "id" text PRIMARY KEY NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "location" text NOT NULL,
  "capacity" integer NOT NULL CHECK ("capacity" > 0),
  "equipment" text DEFAULT '' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','inactive'))
);

CREATE UNIQUE INDEX "spaces_code_unique" ON "spaces" ("code");

CREATE TABLE "bookings" (
  "id" text PRIMARY KEY NOT NULL,
  "request_id" text,
  "requester_id" text NOT NULL,
  "organization" text NOT NULL,
  "space_id" text NOT NULL,
  "title" text NOT NULL,
  "attendee_count" integer NOT NULL CHECK ("attendee_count" > 0),
  "starts_at" integer NOT NULL,
  "ends_at" integer NOT NULL CHECK ("ends_at" > "starts_at"),
  "status" text DEFAULT 'confirmed' NOT NULL CHECK ("status" IN ('confirmed','cancelled')),
  "notes" text DEFAULT '' NOT NULL,
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("request_id") REFERENCES "service_requests"("id"),
  FOREIGN KEY ("requester_id") REFERENCES "users"("id"),
  FOREIGN KEY ("space_id") REFERENCES "spaces"("id")
);

CREATE INDEX "bookings_space_window_idx" ON "bookings" ("space_id","starts_at","ends_at","status");

CREATE INDEX "bookings_requester_idx" ON "bookings" ("requester_id","starts_at");

CREATE TABLE "maintenance_work_orders" (
  "id" text PRIMARY KEY NOT NULL,
  "request_id" text NOT NULL,
  "title" text NOT NULL,
  "location" text NOT NULL,
  "priority" text DEFAULT 'normal' NOT NULL CHECK ("priority" IN ('low','normal','high','critical')),
  "status" text DEFAULT 'open' NOT NULL CHECK ("status" IN ('open','scheduled','in_progress','completed','cancelled')),
  "assigned_to" text,
  "scheduled_at" integer,
  "resolution" text DEFAULT '' NOT NULL,
  "created_by" text NOT NULL,
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("request_id") REFERENCES "service_requests"("id"),
  FOREIGN KEY ("assigned_to") REFERENCES "users"("id"),
  FOREIGN KEY ("created_by") REFERENCES "users"("id")
);

CREATE INDEX "work_orders_status_priority_idx" ON "maintenance_work_orders" ("status","priority","updated_at");

CREATE UNIQUE INDEX "work_orders_active_request_unique" ON "maintenance_work_orders" ("request_id") WHERE "status" <> 'cancelled';

ALTER TABLE "service_requests" ADD "updated_at" integer;

UPDATE "service_requests" SET "updated_at" = "created_at" WHERE "updated_at" IS NULL;

INSERT INTO "spaces" ("id","code","name","location","capacity","equipment","status") VALUES
  ('space-meeting-32','MR-3.2','Phòng họp 3.2','NIC Hòa Lạc · Tầng 3',12,'Họp trực tuyến · Bảng viết','active'),
  ('space-seminar-21','SR-2.1','Phòng hội thảo 2.1','NIC Hòa Lạc · Tầng 2',80,'Màn hình LED · Âm thanh','active'),
  ('space-innovation-hall','INNO-HALL','Innovation Hall','NIC Hòa Lạc · Tầng 1',250,'Sân khấu · Trưng bày · Âm thanh','active');

INSERT INTO "users" ("id","email","full_name","organization","role","password_hash","password_salt","password_iterations","failed_attempts","created_at") VALUES
  ('demo-service-desk-001','desk@demo.nic.vn','Lê Minh Service Desk','NIC','service_desk','HRmOebKvkWNFHk/nYtVLHbblPFDG01IwS09B/PZq7RM=','UZ9cM6ihl20HzLKw7olQqA==',210000,0,1784552400),
  ('demo-facility-001','facility@demo.nic.vn','Trần Anh Facility','NIC','facility_manager','HRmOebKvkWNFHk/nYtVLHbblPFDG01IwS09B/PZq7RM=','UZ9cM6ihl20HzLKw7olQqA==',210000,0,1784552400);

INSERT INTO "organization_memberships" ("id","user_id","organization","department_id","role","status","created_at") VALUES
  ('demo-membership-desk','demo-service-desk-001','NIC','nic-team-service-desk','service_desk','active',1784552400),
  ('demo-membership-facility','demo-facility-001','NIC','nic-team-facility','facility_manager','active',1784552400);

CREATE TABLE "service_providers" (
  "id" text PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "service_types" text NOT NULL,
  "contact_name" text NOT NULL,
  "contact_phone" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','inactive'))
);

CREATE TABLE "visitor_registrations" (
  "id" text PRIMARY KEY NOT NULL,
  "requester_id" text NOT NULL,
  "organization" text NOT NULL,
  "visitor_name" text NOT NULL,
  "visitor_phone" text NOT NULL,
  "host_name" text NOT NULL,
  "visit_at" integer NOT NULL,
  "purpose" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','approved','checked_in','checked_out','cancelled')),
  "badge_code" text NOT NULL UNIQUE,
  "checked_in_at" integer,
  "checked_out_at" integer,
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("requester_id") REFERENCES "users"("id")
);

CREATE INDEX "visitor_visit_status_idx" ON "visitor_registrations" ("visit_at","status");

CREATE TABLE "event_service_orders" (
  "id" text PRIMARY KEY NOT NULL,
  "requester_id" text NOT NULL,
  "organization" text NOT NULL,
  "event_name" text NOT NULL,
  "event_at" integer NOT NULL,
  "attendee_count" integer NOT NULL CHECK ("attendee_count" > 0),
  "catering_package" text NOT NULL CHECK ("catering_package" IN ('none','tea_break_standard','tea_break_premium')),
  "servings" integer NOT NULL CHECK ("servings" >= 0),
  "logistics_notes" text DEFAULT '' NOT NULL,
  "provider_id" text,
  "status" text DEFAULT 'requested' NOT NULL CHECK ("status" IN ('requested','coordinating','confirmed','completed','cancelled')),
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("requester_id") REFERENCES "users"("id"),
  FOREIGN KEY ("provider_id") REFERENCES "service_providers"("id")
);

CREATE INDEX "event_services_event_status_idx" ON "event_service_orders" ("event_at","status");

ALTER TABLE "maintenance_work_orders" ADD "provider_id" text REFERENCES "service_providers"("id");

INSERT INTO "service_providers" ("id","name","service_types","contact_name","contact_phone","status") VALUES
  ('provider-building-mvp','NIC Building Services','maintenance,repair','Nguyễn Văn Minh','024-0000-1001','active'),
  ('provider-catering-mvp','NIC Event Catering','catering,tea_break','Trần Thu Hà','024-0000-1002','active');

INSERT INTO "users" ("id","email","full_name","organization","role","password_hash","password_salt","password_iterations","failed_attempts","created_at") VALUES
  ('demo-event-001','event@demo.nic.vn','Nguyễn Lan Event','NIC','event_manager','HRmOebKvkWNFHk/nYtVLHbblPFDG01IwS09B/PZq7RM=','UZ9cM6ihl20HzLKw7olQqA==',210000,0,1784552400),
  ('demo-security-001','security@demo.nic.vn','Phạm Nam Security','NIC','security_staff','HRmOebKvkWNFHk/nYtVLHbblPFDG01IwS09B/PZq7RM=','UZ9cM6ihl20HzLKw7olQqA==',210000,0,1784552400);

INSERT INTO "organization_memberships" ("id","user_id","organization","department_id","role","status","created_at") VALUES
  ('demo-membership-event','demo-event-001','NIC','nic-team-event','event_manager','active',1784552400),
  ('demo-membership-security','demo-security-001','NIC','nic-team-security','security_staff','active',1784552400);

CREATE TABLE "operation_templates" ("id" text PRIMARY KEY NOT NULL,"service_type" text NOT NULL,"name" text NOT NULL,"version" integer DEFAULT 1 NOT NULL,"status" text DEFAULT 'draft' NOT NULL CHECK ("status" IN ('draft','active','inactive')),"created_by" text NOT NULL,"created_at" integer NOT NULL,FOREIGN KEY ("created_by") REFERENCES "users"("id"));

CREATE UNIQUE INDEX "operation_templates_active_service_unique" ON "operation_templates" ("service_type") WHERE "status"='active';

CREATE TABLE "operation_template_tasks" ("id" text PRIMARY KEY NOT NULL,"template_id" text NOT NULL,"sequence" integer NOT NULL,"title" text NOT NULL,"required" integer DEFAULT 1 NOT NULL,"estimated_minutes" integer DEFAULT 0 NOT NULL,"required_skill" text,"required_materials" text DEFAULT '[]' NOT NULL,FOREIGN KEY ("template_id") REFERENCES "operation_templates"("id") ON DELETE CASCADE);

CREATE UNIQUE INDEX "operation_template_task_sequence_unique" ON "operation_template_tasks" ("template_id","sequence");

CREATE TABLE "work_order_tasks" ("id" text PRIMARY KEY NOT NULL,"work_order_id" text NOT NULL,"template_task_id" text,"sequence" integer NOT NULL,"title" text NOT NULL,"required" integer DEFAULT 1 NOT NULL,"status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','in_progress','completed','skipped')),"completed_by" text,"completed_at" integer,"updated_at" integer NOT NULL,FOREIGN KEY ("work_order_id") REFERENCES "maintenance_work_orders"("id") ON DELETE CASCADE,FOREIGN KEY ("template_task_id") REFERENCES "operation_template_tasks"("id"),FOREIGN KEY ("completed_by") REFERENCES "users"("id"));

CREATE UNIQUE INDEX "work_order_task_sequence_unique" ON "work_order_tasks" ("work_order_id","sequence");

CREATE TABLE "work_order_close_approvals" ("id" text PRIMARY KEY NOT NULL,"work_order_id" text NOT NULL,"requested_by" text NOT NULL,"requested_at" integer NOT NULL,"status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','approved','rejected')),"decided_by" text,"decided_at" integer,"note" text DEFAULT '' NOT NULL,FOREIGN KEY ("work_order_id") REFERENCES "maintenance_work_orders"("id"),FOREIGN KEY ("requested_by") REFERENCES "users"("id"),FOREIGN KEY ("decided_by") REFERENCES "users"("id"));

CREATE UNIQUE INDEX "work_order_pending_close_unique" ON "work_order_close_approvals" ("work_order_id") WHERE "status"='pending';

CREATE TABLE "business_calendars" ("id" text PRIMARY KEY NOT NULL,"name" text NOT NULL,"timezone" text DEFAULT 'Asia/Ho_Chi_Minh' NOT NULL,"working_windows" text NOT NULL,"status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','inactive')));

CREATE TABLE "business_calendar_holidays" ("id" text PRIMARY KEY NOT NULL,"calendar_id" text NOT NULL,"holiday_date" text NOT NULL,"name" text NOT NULL,FOREIGN KEY ("calendar_id") REFERENCES "business_calendars"("id") ON DELETE CASCADE);

CREATE UNIQUE INDEX "business_calendar_holiday_unique" ON "business_calendar_holidays" ("calendar_id","holiday_date");

CREATE TABLE "sla_instances" ("id" text PRIMARY KEY NOT NULL,"work_order_id" text NOT NULL UNIQUE,"calendar_id" text NOT NULL,"warning_at" integer NOT NULL,"due_at" integer NOT NULL,"status" text DEFAULT 'running' NOT NULL CHECK ("status" IN ('running','paused','met','failed')),"paused_at" integer,"paused_seconds" integer DEFAULT 0 NOT NULL,"pause_reason" text,"updated_at" integer NOT NULL,FOREIGN KEY ("work_order_id") REFERENCES "maintenance_work_orders"("id"),FOREIGN KEY ("calendar_id") REFERENCES "business_calendars"("id"));

CREATE TABLE "sla_job_events" ("id" text PRIMARY KEY NOT NULL,"sla_instance_id" text NOT NULL,"event_type" text NOT NULL CHECK ("event_type" IN ('warning','failure','escalation')),"idempotency_key" text NOT NULL UNIQUE,"recipient_scope" text NOT NULL,"created_at" integer NOT NULL,FOREIGN KEY ("sla_instance_id") REFERENCES "sla_instances"("id"));

CREATE TABLE "resource_profiles" ("id" text PRIMARY KEY NOT NULL,"user_id" text,"provider_id" text,"location" text NOT NULL,"timezone" text DEFAULT 'Asia/Ho_Chi_Minh' NOT NULL,"working_windows" text NOT NULL,"status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','inactive')),FOREIGN KEY ("user_id") REFERENCES "users"("id"),FOREIGN KEY ("provider_id") REFERENCES "service_providers"("id"),CHECK (("user_id" IS NOT NULL) <> ("provider_id" IS NOT NULL)));

CREATE TABLE "resource_skills" ("id" text PRIMARY KEY NOT NULL,"resource_id" text NOT NULL,"skill_code" text NOT NULL,"certificate_code" text,"valid_until" integer,FOREIGN KEY ("resource_id") REFERENCES "resource_profiles"("id") ON DELETE CASCADE);

CREATE UNIQUE INDEX "resource_skill_unique" ON "resource_skills" ("resource_id","skill_code");

CREATE TABLE "resource_bookings" ("id" text PRIMARY KEY NOT NULL,"resource_id" text NOT NULL,"work_order_id" text NOT NULL,"starts_at" integer NOT NULL,"ends_at" integer NOT NULL CHECK ("ends_at">"starts_at"),"status" text DEFAULT 'confirmed' NOT NULL CHECK ("status" IN ('confirmed','cancelled')),"created_at" integer NOT NULL,FOREIGN KEY ("resource_id") REFERENCES "resource_profiles"("id"),FOREIGN KEY ("work_order_id") REFERENCES "maintenance_work_orders"("id"));

CREATE INDEX "resource_booking_window_idx" ON "resource_bookings" ("resource_id","starts_at","ends_at","status");

CREATE TABLE "provider_memberships" ("id" text PRIMARY KEY NOT NULL,"provider_id" text NOT NULL,"user_id" text NOT NULL,"status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','inactive')),FOREIGN KEY ("provider_id") REFERENCES "service_providers"("id"),FOREIGN KEY ("user_id") REFERENCES "users"("id"));

CREATE UNIQUE INDEX "provider_membership_unique" ON "provider_memberships" ("provider_id","user_id");

CREATE TABLE "provider_assignments" ("id" text PRIMARY KEY NOT NULL,"work_order_id" text NOT NULL,"provider_id" text NOT NULL,"version" integer DEFAULT 1 NOT NULL,"status" text DEFAULT 'awaiting_provider' NOT NULL CHECK ("status" IN ('awaiting_provider','awaiting_nic','accepted','rejected','expired')),"response_deadline" integer NOT NULL,"promised_at" integer,"response_note" text DEFAULT '' NOT NULL,"responded_by" text,"responded_at" integer,"confirmed_by" text,"confirmed_at" integer,FOREIGN KEY ("work_order_id") REFERENCES "maintenance_work_orders"("id"),FOREIGN KEY ("provider_id") REFERENCES "service_providers"("id"),FOREIGN KEY ("responded_by") REFERENCES "users"("id"),FOREIGN KEY ("confirmed_by") REFERENCES "users"("id"));

CREATE TABLE "provider_assignment_responses" ("id" text PRIMARY KEY NOT NULL,"assignment_id" text NOT NULL,"version" integer NOT NULL,"response" text NOT NULL CHECK ("response" IN ('accept','reject','accept_with_change')),"promised_at" integer,"note" text DEFAULT '' NOT NULL,"actor_id" text NOT NULL,"created_at" integer NOT NULL,FOREIGN KEY ("assignment_id") REFERENCES "provider_assignments"("id") ON DELETE CASCADE,FOREIGN KEY ("actor_id") REFERENCES "users"("id"));

CREATE UNIQUE INDEX "provider_response_version_unique" ON "provider_assignment_responses" ("assignment_id","version");

CREATE TABLE "access_reviews" ("id" text PRIMARY KEY NOT NULL,"organization" text NOT NULL,"scope" text NOT NULL,"status" text DEFAULT 'open' NOT NULL CHECK ("status" IN ('open','completed','overdue')),"deadline" integer NOT NULL,"created_by" text NOT NULL,"created_at" integer NOT NULL,FOREIGN KEY ("created_by") REFERENCES "users"("id"));

CREATE TABLE "access_review_items" ("id" text PRIMARY KEY NOT NULL,"review_id" text NOT NULL,"membership_id" text NOT NULL,"decision" text CHECK ("decision" IN ('retain','revoke')),"evidence" text DEFAULT '' NOT NULL,"reviewed_by" text,"reviewed_at" integer,FOREIGN KEY ("review_id") REFERENCES "access_reviews"("id") ON DELETE CASCADE,FOREIGN KEY ("membership_id") REFERENCES "organization_memberships"("id"),FOREIGN KEY ("reviewed_by") REFERENCES "users"("id"));

CREATE TABLE "configuration_changes" ("id" text PRIMARY KEY NOT NULL,"entity_type" text NOT NULL CHECK ("entity_type" IN ('role','sla','master_data')),"entity_id" text NOT NULL,"payload" text NOT NULL,"reason" text NOT NULL,"maker_id" text NOT NULL,"status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','approved','rejected')),"checker_id" text,"decided_at" integer,"created_at" integer NOT NULL,FOREIGN KEY ("maker_id") REFERENCES "users"("id"),FOREIGN KEY ("checker_id") REFERENCES "users"("id"),CHECK ("checker_id" IS NULL OR "checker_id" <> "maker_id"));

CREATE TABLE "notifications" ("id" text PRIMARY KEY NOT NULL,"recipient_id" text NOT NULL,"type" text NOT NULL,"entity_type" text NOT NULL,"entity_id" text NOT NULL,"dedupe_key" text NOT NULL UNIQUE,"title" text NOT NULL,"body" text NOT NULL,"status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','delivered','failed','read')),"attempts" integer DEFAULT 0 NOT NULL,"created_at" integer NOT NULL,"delivered_at" integer,FOREIGN KEY ("recipient_id") REFERENCES "users"("id"));

INSERT INTO "business_calendars" ("id","name","timezone","working_windows","status") VALUES ('calendar-nic-default','Lịch làm việc NIC','Asia/Ho_Chi_Minh','[{"weekday":1,"startsMinute":480,"endsMinute":1020},{"weekday":2,"startsMinute":480,"endsMinute":1020},{"weekday":3,"startsMinute":480,"endsMinute":1020},{"weekday":4,"startsMinute":480,"endsMinute":1020},{"weekday":5,"startsMinute":480,"endsMinute":1020}]','active');

INSERT INTO "operation_templates" ("id","service_type","name","version","status","created_by","created_at") VALUES ('template-support-v1','support','Quy trình xử lý Facility chuẩn',1,'active','demo-facility-001',1784617200);

INSERT INTO "operation_template_tasks" ("id","template_id","sequence","title","required","estimated_minutes","required_skill","required_materials") VALUES ('template-task-diagnose','template-support-v1',1,'Khảo sát và chẩn đoán',1,30,'facility_general','[]'),('template-task-repair','template-support-v1',2,'Thực hiện xử lý',1,90,'facility_general','[]'),('template-task-verify','template-support-v1',3,'Kiểm tra và ghi nhận kết quả',1,30,'facility_general','[]');

INSERT INTO "resource_profiles" ("id","user_id","location","timezone","working_windows","status") VALUES ('resource-demo-facility','demo-facility-001','NIC Hòa Lạc','Asia/Ho_Chi_Minh','[{"weekday":1,"startsMinute":480,"endsMinute":1020},{"weekday":2,"startsMinute":480,"endsMinute":1020},{"weekday":3,"startsMinute":480,"endsMinute":1020},{"weekday":4,"startsMinute":480,"endsMinute":1020},{"weekday":5,"startsMinute":480,"endsMinute":1020}]','active');

INSERT INTO "resource_skills" ("id","resource_id","skill_code","certificate_code") VALUES ('skill-demo-facility','resource-demo-facility','facility_general','NIC-FAC-001');

INSERT INTO "users" ("id","email","full_name","organization","role","password_hash","password_salt","password_iterations","failed_attempts","created_at") VALUES ('demo-system-admin-001','admin@demo.nic.vn','Quản trị NIC','NIC','system_admin','HRmOebKvkWNFHk/nYtVLHbblPFDG01IwS09B/PZq7RM=','UZ9cM6ihl20HzLKw7olQqA==',210000,0,1784617200),('demo-provider-001','provider@demo.nic.vn','Nguyễn Minh Provider','NIC Building Services','customer_member','HRmOebKvkWNFHk/nYtVLHbblPFDG01IwS09B/PZq7RM=','UZ9cM6ihl20HzLKw7olQqA==',210000,0,1784617200);

INSERT INTO "organization_memberships" ("id","user_id","organization","role","status","created_at") VALUES ('membership-system-admin','demo-system-admin-001','NIC','system_admin','active',1784617200),('membership-provider','demo-provider-001','NIC Building Services','customer_member','active',1784617200);

INSERT INTO "provider_memberships" ("id","provider_id","user_id","status") VALUES ('provider-membership-demo','provider-building-mvp','demo-provider-001','active');

CREATE TABLE "assets" (
  "id" text PRIMARY KEY NOT NULL,
  "organization" text NOT NULL,
  "parent_asset_id" text,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "location" text NOT NULL,
  "category" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','maintenance','retired')),
  "serial_number" text,
  "model" text,
  "provider_id" text,
  "warranty_start" integer,
  "warranty_end" integer,
  "owner_id" text NOT NULL,
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("parent_asset_id") REFERENCES "assets"("id"),
  FOREIGN KEY ("provider_id") REFERENCES "service_providers"("id"),
  FOREIGN KEY ("owner_id") REFERENCES "users"("id"),
  CHECK ("parent_asset_id" IS NULL OR "parent_asset_id" <> "id"),
  CHECK ("warranty_end" IS NULL OR "warranty_start" IS NULL OR "warranty_end" > "warranty_start")
);

CREATE UNIQUE INDEX "assets_org_code_unique" ON "assets" ("organization","code");

CREATE INDEX "assets_parent_idx" ON "assets" ("parent_asset_id");

CREATE TABLE "maintenance_plans" (
  "id" text PRIMARY KEY NOT NULL,
  "asset_id" text NOT NULL,
  "name" text NOT NULL,
  "recurrence_days" integer NOT NULL CHECK ("recurrence_days" BETWEEN 1 AND 3650),
  "lead_time_days" integer DEFAULT 7 NOT NULL CHECK ("lead_time_days" BETWEEN 0 AND 365),
  "booking_window_days" integer DEFAULT 14 NOT NULL CHECK ("booking_window_days" BETWEEN 1 AND 365),
  "next_due_at" integer NOT NULL,
  "template_id" text,
  "status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','paused','inactive')),
  "created_by" text NOT NULL,
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("asset_id") REFERENCES "assets"("id"),
  FOREIGN KEY ("template_id") REFERENCES "operation_templates"("id"),
  FOREIGN KEY ("created_by") REFERENCES "users"("id")
);

CREATE INDEX "maintenance_plans_due_idx" ON "maintenance_plans" ("status","next_due_at");

ALTER TABLE "maintenance_work_orders" ADD COLUMN "asset_id" text REFERENCES "assets"("id");

ALTER TABLE "maintenance_work_orders" ADD COLUMN "maintenance_plan_id" text REFERENCES "maintenance_plans"("id");

CREATE TABLE "maintenance_plan_runs" (
  "id" text PRIMARY KEY NOT NULL,
  "plan_id" text NOT NULL,
  "due_at" integer NOT NULL,
  "work_order_id" text NOT NULL,
  "idempotency_key" text NOT NULL,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("plan_id") REFERENCES "maintenance_plans"("id"),
  FOREIGN KEY ("work_order_id") REFERENCES "maintenance_work_orders"("id")
);

CREATE UNIQUE INDEX "maintenance_plan_run_due_unique" ON "maintenance_plan_runs" ("plan_id","due_at");

CREATE UNIQUE INDEX "maintenance_plan_run_key_unique" ON "maintenance_plan_runs" ("idempotency_key");

CREATE TABLE "work_order_cost_lines" (
  "id" text PRIMARY KEY NOT NULL,
  "work_order_id" text NOT NULL,
  "line_type" text NOT NULL CHECK ("line_type" IN ('labor','material','service')),
  "phase" text NOT NULL CHECK ("phase" IN ('estimate','actual')),
  "description" text NOT NULL,
  "quantity_milli" integer NOT NULL CHECK ("quantity_milli" > 0),
  "unit" text NOT NULL,
  "unit_price_minor" integer NOT NULL CHECK ("unit_price_minor" >= 0),
  "tax_bps" integer DEFAULT 0 NOT NULL CHECK ("tax_bps" BETWEEN 0 AND 10000),
  "discount_bps" integer DEFAULT 0 NOT NULL CHECK ("discount_bps" BETWEEN 0 AND 10000),
  "subtotal_minor" integer NOT NULL,
  "discount_minor" integer NOT NULL,
  "tax_minor" integer NOT NULL,
  "line_total_minor" integer NOT NULL,
  "currency" text DEFAULT 'VND' NOT NULL,
  "catalog_record_id" text,
  "created_by" text NOT NULL,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("work_order_id") REFERENCES "maintenance_work_orders"("id"),
  FOREIGN KEY ("created_by") REFERENCES "users"("id")
);

CREATE INDEX "work_order_cost_phase_idx" ON "work_order_cost_lines" ("work_order_id","phase");

CREATE TABLE "event_templates" (
  "id" text PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "event_type" text NOT NULL,
  "scale" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "budget_threshold_minor" integer DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'draft' NOT NULL CHECK ("status" IN ('draft','active','inactive')),
  "created_by" text NOT NULL,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("created_by") REFERENCES "users"("id")
);

CREATE UNIQUE INDEX "event_template_active_unique" ON "event_templates" ("event_type","scale") WHERE "status"='active';

CREATE TABLE "event_template_tasks" (
  "id" text PRIMARY KEY NOT NULL,
  "template_id" text NOT NULL,
  "sequence" integer NOT NULL,
  "title" text NOT NULL,
  "due_offset_days" integer DEFAULT 0 NOT NULL,
  "dependency_sequence" integer,
  "required" integer DEFAULT 1 NOT NULL,
  "default_assignee_role" text,
  FOREIGN KEY ("template_id") REFERENCES "event_templates"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "event_template_task_sequence_unique" ON "event_template_tasks" ("template_id","sequence");

CREATE TABLE "event_template_lines" (
  "id" text PRIMARY KEY NOT NULL,
  "template_id" text NOT NULL,
  "line_type" text NOT NULL CHECK ("line_type" IN ('menu','equipment','service')),
  "description" text NOT NULL,
  "quantity_milli" integer NOT NULL,
  "unit" text NOT NULL,
  "unit_price_minor" integer NOT NULL,
  FOREIGN KEY ("template_id") REFERENCES "event_templates"("id") ON DELETE CASCADE
);

ALTER TABLE "event_service_orders" ADD COLUMN "template_id" text REFERENCES "event_templates"("id");

ALTER TABLE "event_service_orders" ADD COLUMN "budget_estimate_minor" integer DEFAULT 0 NOT NULL;

ALTER TABLE "event_service_orders" ADD COLUMN "budget_actual_minor" integer DEFAULT 0 NOT NULL;

ALTER TABLE "event_service_orders" ADD COLUMN "budget_threshold_minor" integer DEFAULT 0 NOT NULL;

ALTER TABLE "event_service_orders" ADD COLUMN "budget_status" text DEFAULT 'not_required' NOT NULL CHECK ("budget_status" IN ('not_required','pending','approved','rejected'));

CREATE TABLE "event_checklist_tasks" (
  "id" text PRIMARY KEY NOT NULL,
  "event_order_id" text NOT NULL,
  "source_template_task_id" text,
  "sequence" integer NOT NULL,
  "title" text NOT NULL,
  "due_at" integer NOT NULL,
  "depends_on_task_id" text,
  "required" integer DEFAULT 1 NOT NULL,
  "assignee_id" text,
  "status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','in_progress','completed','skipped')),
  "completed_by" text,
  "completed_at" integer,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("event_order_id") REFERENCES "event_service_orders"("id") ON DELETE CASCADE,
  FOREIGN KEY ("source_template_task_id") REFERENCES "event_template_tasks"("id"),
  FOREIGN KEY ("depends_on_task_id") REFERENCES "event_checklist_tasks"("id"),
  FOREIGN KEY ("assignee_id") REFERENCES "users"("id"),
  FOREIGN KEY ("completed_by") REFERENCES "users"("id")
);

CREATE UNIQUE INDEX "event_checklist_sequence_unique" ON "event_checklist_tasks" ("event_order_id","sequence");

CREATE TABLE "event_budget_lines" (
  "id" text PRIMARY KEY NOT NULL,
  "event_order_id" text NOT NULL,
  "source_template_line_id" text,
  "line_type" text NOT NULL,
  "description" text NOT NULL,
  "quantity_milli" integer NOT NULL,
  "unit" text NOT NULL,
  "unit_price_minor" integer NOT NULL,
  "line_total_minor" integer NOT NULL,
  "phase" text DEFAULT 'estimate' NOT NULL CHECK ("phase" IN ('estimate','actual')),
  "created_at" integer NOT NULL,
  FOREIGN KEY ("event_order_id") REFERENCES "event_service_orders"("id") ON DELETE CASCADE,
  FOREIGN KEY ("source_template_line_id") REFERENCES "event_template_lines"("id")
);

CREATE TABLE "event_budget_approvals" (
  "id" text PRIMARY KEY NOT NULL,
  "event_order_id" text NOT NULL,
  "requested_by" text NOT NULL,
  "requested_at" integer NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','approved','rejected')),
  "decided_by" text,
  "decided_at" integer,
  "note" text DEFAULT '' NOT NULL,
  FOREIGN KEY ("event_order_id") REFERENCES "event_service_orders"("id"),
  FOREIGN KEY ("requested_by") REFERENCES "users"("id"),
  FOREIGN KEY ("decided_by") REFERENCES "users"("id"),
  CHECK ("decided_by" IS NULL OR "decided_by" <> "requested_by")
);

CREATE UNIQUE INDEX "event_budget_pending_unique" ON "event_budget_approvals" ("event_order_id") WHERE "status"='pending';

CREATE TABLE "access_zones" (
  "id" text PRIMARY KEY NOT NULL,
  "code" text NOT NULL UNIQUE,
  "name" text NOT NULL,
  "controller_ref" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','inactive'))
);

ALTER TABLE "visitor_registrations" ADD COLUMN "access_zone_id" text REFERENCES "access_zones"("id");

CREATE TABLE "visitor_qr_tokens" (
  "id" text PRIMARY KEY NOT NULL,
  "visitor_id" text NOT NULL,
  "token_hash" text NOT NULL UNIQUE,
  "expires_at" integer NOT NULL,
  "redeemed_at" integer,
  "redeemed_by" text,
  "created_by" text NOT NULL,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("visitor_id") REFERENCES "visitor_registrations"("id") ON DELETE CASCADE,
  FOREIGN KEY ("redeemed_by") REFERENCES "users"("id"),
  FOREIGN KEY ("created_by") REFERENCES "users"("id")
);

CREATE TABLE "badge_print_jobs" (
  "id" text PRIMARY KEY NOT NULL,
  "visitor_id" text NOT NULL,
  "template_version" integer DEFAULT 1 NOT NULL,
  "printer_ref" text NOT NULL,
  "status" text DEFAULT 'queued' NOT NULL CHECK ("status" IN ('queued','printed','failed')),
  "is_reprint" integer DEFAULT 0 NOT NULL,
  "reason" text NOT NULL,
  "render_payload" text NOT NULL,
  "actor_id" text NOT NULL,
  "created_at" integer NOT NULL,
  "printed_at" integer,
  FOREIGN KEY ("visitor_id") REFERENCES "visitor_registrations"("id"),
  FOREIGN KEY ("actor_id") REFERENCES "users"("id")
);

CREATE TABLE "visitor_access_grants" (
  "id" text PRIMARY KEY NOT NULL,
  "visitor_id" text NOT NULL,
  "access_zone_id" text NOT NULL,
  "valid_from" integer NOT NULL,
  "valid_until" integer NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','active','revoked','expired','offline_hold')),
  "controller_grant_ref" text,
  "created_at" integer NOT NULL,
  "revoked_at" integer,
  FOREIGN KEY ("visitor_id") REFERENCES "visitor_registrations"("id"),
  FOREIGN KEY ("access_zone_id") REFERENCES "access_zones"("id")
);

CREATE UNIQUE INDEX "visitor_active_grant_unique" ON "visitor_access_grants" ("visitor_id","access_zone_id") WHERE "status" IN ('pending','active');

CREATE TABLE "access_controller_events" (
  "id" text PRIMARY KEY NOT NULL,
  "visitor_id" text NOT NULL,
  "access_grant_id" text,
  "event_type" text NOT NULL CHECK ("event_type" IN ('grant','revoke','offline_hold','override')),
  "controller_ref" text,
  "status" text NOT NULL CHECK ("status" IN ('queued','sent','acknowledged','failed','manual_review')),
  "reason" text NOT NULL,
  "actor_id" text NOT NULL,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("visitor_id") REFERENCES "visitor_registrations"("id"),
  FOREIGN KEY ("access_grant_id") REFERENCES "visitor_access_grants"("id"),
  FOREIGN KEY ("actor_id") REFERENCES "users"("id")
);

CREATE TABLE "master_data_records" (
  "id" text PRIMARY KEY NOT NULL,
  "entity_type" text NOT NULL CHECK ("entity_type" IN ('asset_category','cost_catalog','provider','access_zone','event_catalog')),
  "record_key" text NOT NULL,
  "version" integer NOT NULL,
  "status" text DEFAULT 'draft' NOT NULL CHECK ("status" IN ('draft','approved','inactive','rejected')),
  "owner_id" text NOT NULL,
  "effective_from" integer NOT NULL,
  "effective_to" integer,
  "payload" text NOT NULL,
  "reason" text NOT NULL,
  "maker_id" text NOT NULL,
  "checker_id" text,
  "decided_at" integer,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("owner_id") REFERENCES "users"("id"),
  FOREIGN KEY ("maker_id") REFERENCES "users"("id"),
  FOREIGN KEY ("checker_id") REFERENCES "users"("id"),
  CHECK ("checker_id" IS NULL OR "checker_id" <> "maker_id"),
  CHECK ("effective_to" IS NULL OR "effective_to" > "effective_from")
);

CREATE UNIQUE INDEX "master_data_record_version_unique" ON "master_data_records" ("entity_type","record_key","version");

CREATE UNIQUE INDEX "master_data_effective_unique" ON "master_data_records" ("entity_type","record_key") WHERE "status"='approved' AND "effective_to" IS NULL;

INSERT INTO "assets" ("id","organization","code","name","location","category","status","serial_number","model","provider_id","warranty_start","warranty_end","owner_id","created_at","updated_at") VALUES ('asset-hvac-demo','NIC','HVAC-HL-01','Cụm điều hòa trung tâm Hòa Lạc','NIC Hòa Lạc · Tầng 1','HVAC','active','NIC-HVAC-0001','VRV-X','provider-building-mvp',1751328000,1814400000,'demo-facility-001',1784617200,1784617200);

INSERT INTO "maintenance_plans" ("id","asset_id","name","recurrence_days","lead_time_days","booking_window_days","next_due_at","template_id","status","created_by","created_at","updated_at") VALUES ('plan-hvac-demo','asset-hvac-demo','Bảo trì HVAC định kỳ',90,7,14,1785222000,'template-support-v1','active','demo-facility-001',1784617200,1784617200);

INSERT INTO "event_templates" ("id","name","event_type","scale","version","budget_threshold_minor","status","created_by","created_at") VALUES ('event-template-workshop-v1','Workshop tiêu chuẩn','workshop','medium',1,50000000,'active','demo-event-001',1784617200);

INSERT INTO "event_template_tasks" ("id","template_id","sequence","title","due_offset_days","dependency_sequence","required","default_assignee_role") VALUES ('event-task-plan','event-template-workshop-v1',1,'Chốt mặt bằng và sơ đồ',-7,NULL,1,'event_staff'),('event-task-equipment','event-template-workshop-v1',2,'Kiểm tra thiết bị',-2,1,1,'event_staff'),('event-task-catering','event-template-workshop-v1',3,'Xác nhận catering',-1,1,1,'event_staff');

INSERT INTO "event_template_lines" ("id","template_id","line_type","description","quantity_milli","unit","unit_price_minor") VALUES ('event-line-room','event-template-workshop-v1','service','Vận hành hội trường',1000,'gói',15000000),('event-line-equipment','event-template-workshop-v1','equipment','Âm thanh và trình chiếu',1000,'gói',12000000),('event-line-menu','event-template-workshop-v1','menu','Tea break tiêu chuẩn',100000,'suất',180000);

INSERT INTO "access_zones" ("id","code","name","controller_ref","status") VALUES ('zone-reception-demo','RECEPTION','Sảnh và khu tiếp khách','controller-nic-demo','active');

INSERT INTO "master_data_records" ("id","entity_type","record_key","version","status","owner_id","effective_from","payload","reason","maker_id","checker_id","decided_at","created_at") VALUES ('master-asset-category-hvac','asset_category','HVAC',1,'approved','demo-system-admin-001',1784617200,'{"name":"HVAC","maintenanceRequired":true}','Seed danh mục P2','demo-system-admin-001','demo-facility-001',1784617200,1784617200);

ALTER TABLE "users" ADD COLUMN "account_status" text DEFAULT 'active' NOT NULL CHECK ("account_status" IN ('invited','active','suspended','deprovisioned'));

ALTER TABLE "users" ADD COLUMN "identity_provider" text DEFAULT 'local' NOT NULL;

ALTER TABLE "users" ADD COLUMN "identity_subject" text;

ALTER TABLE "users" ADD COLUMN "mfa_required" integer DEFAULT 0 NOT NULL;

CREATE UNIQUE INDEX "users_external_identity_unique" ON "users" ("identity_provider","identity_subject") WHERE "identity_subject" IS NOT NULL;

ALTER TABLE "sessions" ADD COLUMN "auth_method" text DEFAULT 'local' NOT NULL CHECK ("auth_method" IN ('local','federated'));

ALTER TABLE "sessions" ADD COLUMN "mfa_verified" integer DEFAULT 0 NOT NULL;

ALTER TABLE "audit_logs" ADD COLUMN "correlation_id" text;

ALTER TABLE "audit_logs" ADD COLUMN "source" text DEFAULT 'application' NOT NULL;

CREATE TABLE "oidc_login_attempts" (
  "id" text PRIMARY KEY NOT NULL,
  "state_hash" text NOT NULL UNIQUE,
  "nonce_hash" text NOT NULL,
  "code_verifier" text NOT NULL,
  "return_to" text DEFAULT '/portal' NOT NULL,
  "expires_at" integer NOT NULL,
  "consumed_at" integer,
  "created_at" integer NOT NULL
);

CREATE TABLE "finance_policies" (
  "id" text PRIMARY KEY NOT NULL,
  "organization" text NOT NULL UNIQUE,
  "currency" text DEFAULT 'VND' NOT NULL,
  "po_approval_threshold_minor" integer NOT NULL CHECK ("po_approval_threshold_minor" >= 0),
  "price_tolerance_bps" integer DEFAULT 500 NOT NULL CHECK ("price_tolerance_bps" BETWEEN 0 AND 10000),
  "quantity_tolerance_bps" integer DEFAULT 0 NOT NULL CHECK ("quantity_tolerance_bps" BETWEEN 0 AND 10000),
  "updated_by" text NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("updated_by") REFERENCES "users"("id")
);

CREATE TABLE "procurement_contracts" (
  "id" text PRIMARY KEY NOT NULL,
  "organization" text NOT NULL,
  "contract_number" text NOT NULL,
  "provider_id" text NOT NULL,
  "title" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "status" text DEFAULT 'draft' NOT NULL CHECK ("status" IN ('draft','active','expired','terminated')),
  "currency" text DEFAULT 'VND' NOT NULL,
  "valid_from" integer NOT NULL,
  "valid_until" integer NOT NULL,
  "ceiling_minor" integer NOT NULL CHECK ("ceiling_minor" >= 0),
  "created_by" text NOT NULL,
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("provider_id") REFERENCES "service_providers"("id"),
  FOREIGN KEY ("created_by") REFERENCES "users"("id"),
  CHECK ("valid_until" > "valid_from")
);

CREATE UNIQUE INDEX "procurement_contract_version_unique" ON "procurement_contracts" ("organization","contract_number","version");

CREATE TABLE "procurement_contract_lines" (
  "id" text PRIMARY KEY NOT NULL,
  "contract_id" text NOT NULL,
  "line_number" integer NOT NULL,
  "description" text NOT NULL,
  "unit" text NOT NULL,
  "max_quantity_milli" integer NOT NULL CHECK ("max_quantity_milli" > 0),
  "unit_price_minor" integer NOT NULL CHECK ("unit_price_minor" >= 0),
  FOREIGN KEY ("contract_id") REFERENCES "procurement_contracts"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "procurement_contract_line_unique" ON "procurement_contract_lines" ("contract_id","line_number");

CREATE TABLE "purchase_orders" (
  "id" text PRIMARY KEY NOT NULL,
  "organization" text NOT NULL,
  "po_number" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "provider_id" text NOT NULL,
  "contract_id" text,
  "work_order_id" text,
  "event_order_id" text,
  "status" text DEFAULT 'draft' NOT NULL CHECK ("status" IN ('draft','pending_approval','approved','rejected','issued','partially_received','received','closed','cancelled')),
  "currency" text DEFAULT 'VND' NOT NULL,
  "subtotal_minor" integer NOT NULL CHECK ("subtotal_minor" >= 0),
  "approval_threshold_minor" integer NOT NULL CHECK ("approval_threshold_minor" >= 0),
  "idempotency_key" text NOT NULL,
  "created_by" text NOT NULL,
  "approved_by" text,
  "approved_at" integer,
  "issued_at" integer,
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("provider_id") REFERENCES "service_providers"("id"),
  FOREIGN KEY ("contract_id") REFERENCES "procurement_contracts"("id"),
  FOREIGN KEY ("work_order_id") REFERENCES "maintenance_work_orders"("id"),
  FOREIGN KEY ("event_order_id") REFERENCES "event_service_orders"("id"),
  FOREIGN KEY ("created_by") REFERENCES "users"("id"),
  FOREIGN KEY ("approved_by") REFERENCES "users"("id"),
  CHECK ("work_order_id" IS NOT NULL OR "event_order_id" IS NOT NULL)
);

CREATE UNIQUE INDEX "purchase_order_number_version_unique" ON "purchase_orders" ("organization","po_number","version");

CREATE UNIQUE INDEX "purchase_order_idempotency_unique" ON "purchase_orders" ("organization","idempotency_key");

CREATE TABLE "purchase_order_lines" (
  "id" text PRIMARY KEY NOT NULL,
  "purchase_order_id" text NOT NULL,
  "contract_line_id" text,
  "line_number" integer NOT NULL,
  "description" text NOT NULL,
  "line_type" text DEFAULT 'service' NOT NULL CHECK ("line_type" IN ('labor','material','service','equipment','menu')),
  "quantity_milli" integer NOT NULL CHECK ("quantity_milli" > 0),
  "unit" text NOT NULL,
  "unit_price_minor" integer NOT NULL CHECK ("unit_price_minor" >= 0),
  "line_total_minor" integer NOT NULL CHECK ("line_total_minor" >= 0),
  FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE,
  FOREIGN KEY ("contract_line_id") REFERENCES "procurement_contract_lines"("id")
);

CREATE UNIQUE INDEX "purchase_order_line_unique" ON "purchase_order_lines" ("purchase_order_id","line_number");

CREATE TABLE "purchase_order_approvals" (
  "id" text PRIMARY KEY NOT NULL,
  "purchase_order_id" text NOT NULL UNIQUE,
  "requested_by" text NOT NULL,
  "requested_at" integer NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL CHECK ("status" IN ('pending','approved','rejected')),
  "decided_by" text,
  "decided_at" integer,
  "note" text DEFAULT '' NOT NULL,
  FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE,
  FOREIGN KEY ("requested_by") REFERENCES "users"("id"),
  FOREIGN KEY ("decided_by") REFERENCES "users"("id"),
  CHECK ("decided_by" IS NULL OR "decided_by" <> "requested_by")
);

CREATE TABLE "goods_receipts" (
  "id" text PRIMARY KEY NOT NULL,
  "purchase_order_id" text NOT NULL,
  "receipt_number" text NOT NULL,
  "status" text DEFAULT 'posted' NOT NULL CHECK ("status" IN ('posted','reversed')),
  "received_at" integer NOT NULL,
  "idempotency_key" text NOT NULL,
  "received_by" text NOT NULL,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id"),
  FOREIGN KEY ("received_by") REFERENCES "users"("id")
);

CREATE UNIQUE INDEX "goods_receipt_number_unique" ON "goods_receipts" ("purchase_order_id","receipt_number");

CREATE UNIQUE INDEX "goods_receipt_idempotency_unique" ON "goods_receipts" ("purchase_order_id","idempotency_key");

CREATE TABLE "goods_receipt_lines" (
  "id" text PRIMARY KEY NOT NULL,
  "receipt_id" text NOT NULL,
  "purchase_order_line_id" text NOT NULL,
  "quantity_received_milli" integer NOT NULL CHECK ("quantity_received_milli" > 0),
  "condition" text DEFAULT 'accepted' NOT NULL CHECK ("condition" IN ('accepted','damaged','rejected')),
  "note" text DEFAULT '' NOT NULL,
  FOREIGN KEY ("receipt_id") REFERENCES "goods_receipts"("id") ON DELETE CASCADE,
  FOREIGN KEY ("purchase_order_line_id") REFERENCES "purchase_order_lines"("id")
);

CREATE UNIQUE INDEX "goods_receipt_line_unique" ON "goods_receipt_lines" ("receipt_id","purchase_order_line_id");

CREATE TABLE "supplier_invoices" (
  "id" text PRIMARY KEY NOT NULL,
  "purchase_order_id" text NOT NULL,
  "provider_id" text NOT NULL,
  "invoice_number" text NOT NULL,
  "invoice_date" integer NOT NULL,
  "status" text DEFAULT 'pending_match' NOT NULL CHECK ("status" IN ('pending_match','matched','exception','approved','rejected','paid')),
  "currency" text NOT NULL,
  "total_minor" integer NOT NULL CHECK ("total_minor" >= 0),
  "idempotency_key" text NOT NULL,
  "created_by" text NOT NULL,
  "created_at" integer NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id"),
  FOREIGN KEY ("provider_id") REFERENCES "service_providers"("id"),
  FOREIGN KEY ("created_by") REFERENCES "users"("id")
);

CREATE UNIQUE INDEX "supplier_invoice_number_unique" ON "supplier_invoices" ("provider_id","invoice_number");

CREATE UNIQUE INDEX "supplier_invoice_idempotency_unique" ON "supplier_invoices" ("provider_id","idempotency_key");

CREATE TABLE "supplier_invoice_lines" (
  "id" text PRIMARY KEY NOT NULL,
  "invoice_id" text NOT NULL,
  "purchase_order_line_id" text NOT NULL,
  "line_number" integer NOT NULL,
  "quantity_milli" integer NOT NULL CHECK ("quantity_milli" > 0),
  "unit_price_minor" integer NOT NULL CHECK ("unit_price_minor" >= 0),
  "line_total_minor" integer NOT NULL CHECK ("line_total_minor" >= 0),
  FOREIGN KEY ("invoice_id") REFERENCES "supplier_invoices"("id") ON DELETE CASCADE,
  FOREIGN KEY ("purchase_order_line_id") REFERENCES "purchase_order_lines"("id")
);

CREATE UNIQUE INDEX "supplier_invoice_line_unique" ON "supplier_invoice_lines" ("invoice_id","line_number");

CREATE TABLE "three_way_matches" (
  "id" text PRIMARY KEY NOT NULL,
  "invoice_id" text NOT NULL UNIQUE,
  "status" text NOT NULL CHECK ("status" IN ('matched','exception')),
  "price_tolerance_bps" integer NOT NULL,
  "quantity_tolerance_bps" integer NOT NULL,
  "variance_minor" integer NOT NULL,
  "result_payload" text NOT NULL,
  "matched_by" text NOT NULL,
  "matched_at" integer NOT NULL,
  FOREIGN KEY ("invoice_id") REFERENCES "supplier_invoices"("id"),
  FOREIGN KEY ("matched_by") REFERENCES "users"("id")
);

CREATE TABLE "procurement_exceptions" (
  "id" text PRIMARY KEY NOT NULL,
  "invoice_id" text NOT NULL,
  "exception_type" text NOT NULL,
  "severity" text DEFAULT 'high' NOT NULL CHECK ("severity" IN ('medium','high','critical')),
  "status" text DEFAULT 'open' NOT NULL CHECK ("status" IN ('open','under_review','resolved','rejected')),
  "details" text NOT NULL,
  "assigned_role" text DEFAULT 'finance_manager' NOT NULL,
  "created_at" integer NOT NULL,
  "resolved_by" text,
  "resolved_at" integer,
  FOREIGN KEY ("invoice_id") REFERENCES "supplier_invoices"("id"),
  FOREIGN KEY ("resolved_by") REFERENCES "users"("id")
);

CREATE TABLE "observability_events" (
  "id" text PRIMARY KEY NOT NULL,
  "correlation_id" text NOT NULL,
  "trace_id" text NOT NULL,
  "level" text NOT NULL CHECK ("level" IN ('info','warn','error')),
  "event_name" text NOT NULL,
  "route" text NOT NULL,
  "actor_hash" text,
  "status_code" integer,
  "duration_ms" integer,
  "error_code" text,
  "metadata" text DEFAULT '{}' NOT NULL,
  "created_at" integer NOT NULL
);

CREATE INDEX "observability_correlation_idx" ON "observability_events" ("correlation_id","created_at");

CREATE TABLE "operational_incidents" (
  "id" text PRIMARY KEY NOT NULL,
  "correlation_id" text NOT NULL,
  "source" text NOT NULL,
  "severity" text NOT NULL CHECK ("severity" IN ('warning','critical')),
  "title" text NOT NULL,
  "status" text DEFAULT 'open' NOT NULL CHECK ("status" IN ('open','acknowledged','resolved')),
  "runbook" text NOT NULL,
  "dedupe_key" text NOT NULL UNIQUE,
  "created_at" integer NOT NULL,
  "resolved_at" integer
);

CREATE TABLE "retention_policies" (
  "id" text PRIMARY KEY NOT NULL,
  "data_class" text NOT NULL UNIQUE,
  "retention_days" integer NOT NULL CHECK ("retention_days" > 0),
  "action" text NOT NULL CHECK ("action" IN ('archive_delete','delete','anonymize')),
  "legal_basis" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','inactive')),
  "updated_by" text NOT NULL,
  "updated_at" integer NOT NULL,
  FOREIGN KEY ("updated_by") REFERENCES "users"("id")
);

CREATE TABLE "legal_holds" (
  "id" text PRIMARY KEY NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL,
  "reason" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('active','released')),
  "created_by" text NOT NULL,
  "created_at" integer NOT NULL,
  "released_by" text,
  "released_at" integer,
  FOREIGN KEY ("created_by") REFERENCES "users"("id"),
  FOREIGN KEY ("released_by") REFERENCES "users"("id")
);

CREATE UNIQUE INDEX "legal_hold_active_unique" ON "legal_holds" ("entity_type","entity_id") WHERE "status"='active';

CREATE TABLE "retention_job_runs" (
  "id" text PRIMARY KEY NOT NULL,
  "correlation_id" text NOT NULL,
  "dry_run" integer DEFAULT 1 NOT NULL,
  "status" text NOT NULL CHECK ("status" IN ('running','completed','failed')),
  "candidate_count" integer DEFAULT 0 NOT NULL,
  "processed_count" integer DEFAULT 0 NOT NULL,
  "held_count" integer DEFAULT 0 NOT NULL,
  "error_code" text,
  "started_at" integer NOT NULL,
  "completed_at" integer
);

CREATE TABLE "retention_archive" (
  "id" text PRIMARY KEY NOT NULL,
  "job_run_id" text NOT NULL,
  "data_class" text NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL,
  "payload" text NOT NULL,
  "payload_hash" text NOT NULL,
  "archived_at" integer NOT NULL,
  FOREIGN KEY ("job_run_id") REFERENCES "retention_job_runs"("id")
);

INSERT INTO "finance_policies" ("id","organization","currency","po_approval_threshold_minor","price_tolerance_bps","quantity_tolerance_bps","updated_by","updated_at") VALUES ('finance-policy-nic','NIC','VND',50000000,500,0,'demo-system-admin-001',1784617200);

INSERT INTO "retention_policies" ("id","data_class","retention_days","action","legal_basis","updated_by","updated_at") VALUES ('retention-auth-session','auth_session',30,'delete','Bảo mật và quản trị phiên','demo-system-admin-001',1784617200),('retention-visitor-qr','visitor_qr',30,'archive_delete','An toàn truy cập và kiểm toán','demo-system-admin-001',1784617200),('retention-observability','observability',90,'delete','Vận hành và điều tra sự cố','demo-system-admin-001',1784617200);

CREATE TABLE "sessions_v2" (
  "id" text PRIMARY KEY NOT NULL,
  "user_id" text NOT NULL,
  "token_hash" text NOT NULL,
  "csrf_hash" text DEFAULT '' NOT NULL,
  "auth_method" text DEFAULT 'local' NOT NULL CHECK ("auth_method" IN ('local','federated')),
  "mfa_verified" integer DEFAULT 0 NOT NULL,
  "expires_at" integer NOT NULL,
  "created_at" integer NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE cascade
);

INSERT INTO "sessions_v2" ("id","user_id","token_hash","csrf_hash","auth_method","mfa_verified","expires_at","created_at")
SELECT "id","user_id","token_hash","csrf_hash",CASE WHEN "auth_method"='oidc' THEN 'federated' ELSE 'local' END,"mfa_verified","expires_at","created_at" FROM "sessions";

DROP TABLE "sessions";

ALTER TABLE "sessions_v2" RENAME TO "sessions";

CREATE UNIQUE INDEX "sessions_token_hash_unique" ON "sessions" ("token_hash");

CREATE TABLE "diagnostic_reports" (
  "id" text PRIMARY KEY NOT NULL,
  "correlation_id" text NOT NULL,
  "trace_id" text NOT NULL,
  "route" text NOT NULL,
  "error_class" text NOT NULL,
  "error_code" text NOT NULL,
  "safe_message" text NOT NULL,
  "frames" text NOT NULL,
  "actor_hash" text,
  "created_at" integer NOT NULL
);

CREATE INDEX "diagnostic_reports_correlation_idx" ON "diagnostic_reports" ("correlation_id","created_at");

CREATE TABLE "knowledge_documents" (
  "id" text PRIMARY KEY NOT NULL,
  "service_type" text NOT NULL,
  "title" text NOT NULL,
  "content" text NOT NULL,
  "source_uri" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "status" text DEFAULT 'active' NOT NULL CHECK ("status" IN ('draft','active','retired')),
  "updated_at" integer NOT NULL
);

CREATE INDEX "knowledge_documents_service_status_idx" ON "knowledge_documents" ("service_type","status");

INSERT INTO "knowledge_documents" ("id","service_type","title","content","source_uri","version","status","updated_at") VALUES
('knowledge-space-v1','space_booking','Danh mục không gian NIC','Chọn không gian theo ngày, giờ bắt đầu, giờ kết thúc, số người và thiết bị. Hệ thống kiểm tra sức chứa và lịch trống trước khi xác nhận.','/portal/bookings',1,'active',1784617200),
('knowledge-support-v1','support','Hướng dẫn hỗ trợ cơ sở vật chất','Mô tả vị trí, mức ảnh hưởng, mức ưu tiên và thời gian mong muốn. Yêu cầu sau khi gửi được chuyển tới Facility để tạo và lập lịch lệnh công việc.','/portal/requests',1,'active',1784617200),
('knowledge-event-v1','event_registration','Hướng dẫn sự kiện và tea break','Khai báo tên sự kiện, thời gian, số người, gói tea break, số suất và ghi chú hậu cần. Event team điều phối nhà cung cấp trước khi xác nhận.','/portal/coordination',1,'active',1784617200),
('knowledge-access-v1','access_card','Hướng dẫn khách và quyền ra vào','Đăng ký khách cần họ tên, liên hệ, người tiếp đón, thời gian và mục đích. Khách được phê duyệt mới có thể nhận QR hoặc badge.','/portal/coordination',1,'active',1784617200);

CREATE TABLE "request_comments" (
  "id" text PRIMARY KEY NOT NULL,
  "request_id" text NOT NULL,
  "author_id" text NOT NULL,
  "body" text NOT NULL CHECK (length("body") BETWEEN 1 AND 2000),
  "created_at" integer NOT NULL,
  FOREIGN KEY ("request_id") REFERENCES "service_requests"("id") ON DELETE CASCADE,
  FOREIGN KEY ("author_id") REFERENCES "users"("id")
);

CREATE INDEX "request_comments_request_time_idx" ON "request_comments" ("request_id","created_at");

CREATE TABLE "request_attachments" (
  "id" text PRIMARY KEY NOT NULL,
  "request_id" text NOT NULL,
  "uploaded_by" text NOT NULL,
  "object_key" text NOT NULL,
  "original_name" text NOT NULL,
  "content_type" text NOT NULL,
  "size_bytes" integer NOT NULL CHECK ("size_bytes" BETWEEN 1 AND 8388608),
  "sha256" text NOT NULL,
  "validation_status" text DEFAULT 'validated' NOT NULL CHECK ("validation_status" IN ('validated','rejected','quarantined')),
  "created_at" integer NOT NULL,
  FOREIGN KEY ("request_id") REFERENCES "service_requests"("id") ON DELETE CASCADE,
  FOREIGN KEY ("uploaded_by") REFERENCES "users"("id")
);

CREATE UNIQUE INDEX "request_attachments_object_key_unique" ON "request_attachments" ("object_key");

CREATE INDEX "request_attachments_request_time_idx" ON "request_attachments" ("request_id","created_at");

ALTER TABLE "request_attachments" ADD "scan_attempts" integer DEFAULT 0 NOT NULL;

ALTER TABLE "request_attachments" ADD "last_scan_error" text;

ALTER TABLE "request_attachments" ADD "scanned_at" integer;

CREATE INDEX "request_attachments_scan_queue_idx" ON "request_attachments" ("validation_status","scan_attempts","created_at");


CREATE OR REPLACE FUNCTION nic_app.reject_resource_booking_overlap()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = 'confirmed' AND EXISTS (
    SELECT 1 FROM nic_app.resource_bookings booking
    WHERE booking.resource_id = NEW.resource_id
      AND booking.status = 'confirmed'
      AND booking.starts_at < NEW.ends_at
      AND booking.ends_at > NEW.starts_at
  ) THEN
    RAISE EXCEPTION 'RESOURCE_BOOKING_OVERLAP' USING ERRCODE = '23P01';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER resource_booking_no_overlap_insert
BEFORE INSERT OR UPDATE OF resource_id, starts_at, ends_at, status
ON nic_app.resource_bookings FOR EACH ROW EXECUTE FUNCTION nic_app.reject_resource_booking_overlap();

CREATE OR REPLACE FUNCTION nic_app.reject_cost_snapshot_update()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'COST_SNAPSHOT_IMMUTABLE' USING ERRCODE = '23000';
END;
$$;
CREATE TRIGGER work_order_cost_snapshot_immutable
BEFORE UPDATE OF quantity_milli, unit_price_minor, tax_bps, discount_bps,
  subtotal_minor, discount_minor, tax_minor, line_total_minor, currency, catalog_record_id
ON nic_app.work_order_cost_lines FOR EACH ROW EXECUTE FUNCTION nic_app.reject_cost_snapshot_update();

CREATE OR REPLACE FUNCTION nic_app.reject_qr_replay()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.redeemed_at IS NOT NULL THEN
    RAISE EXCEPTION 'QR_ALREADY_REDEEMED' USING ERRCODE = '23000';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER visitor_qr_no_replay
BEFORE UPDATE OF redeemed_at ON nic_app.visitor_qr_tokens
FOR EACH ROW EXECUTE FUNCTION nic_app.reject_qr_replay();

CREATE OR REPLACE FUNCTION nic_app.reject_master_data_hard_delete()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.status <> 'draft' THEN
    RAISE EXCEPTION 'MASTER_DATA_HARD_DELETE_FORBIDDEN' USING ERRCODE = '23000';
  END IF;
  RETURN OLD;
END;
$$;
CREATE TRIGGER master_data_no_hard_delete
BEFORE DELETE ON nic_app.master_data_records
FOR EACH ROW EXECUTE FUNCTION nic_app.reject_master_data_hard_delete();

CREATE OR REPLACE FUNCTION nic_app.guard_purchase_order_issue()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = 'issued' AND (OLD.status <> 'approved' OR NEW.approved_by IS NULL) THEN
    RAISE EXCEPTION 'PO_APPROVAL_REQUIRED' USING ERRCODE = '23000';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER purchase_order_issue_guard
BEFORE UPDATE OF status ON nic_app.purchase_orders
FOR EACH ROW EXECUTE FUNCTION nic_app.guard_purchase_order_issue();

CREATE OR REPLACE FUNCTION nic_app.guard_goods_receipt_quantity()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  ordered bigint;
  received bigint;
BEGIN
  SELECT quantity_milli INTO ordered
  FROM nic_app.purchase_order_lines WHERE id = NEW.purchase_order_line_id;
  SELECT COALESCE(sum(line.quantity_received_milli), 0) INTO received
  FROM nic_app.goods_receipt_lines line
  JOIN nic_app.goods_receipts receipt ON receipt.id = line.receipt_id
  WHERE line.purchase_order_line_id = NEW.purchase_order_line_id
    AND receipt.status = 'posted';
  IF received + NEW.quantity_received_milli > ordered THEN
    RAISE EXCEPTION 'RECEIPT_EXCEEDS_PO' USING ERRCODE = '23000';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER goods_receipt_quantity_guard
BEFORE INSERT OR UPDATE OF quantity_received_milli ON nic_app.goods_receipt_lines
FOR EACH ROW EXECUTE FUNCTION nic_app.guard_goods_receipt_quantity();


CREATE TABLE IF NOT EXISTS nic_app.schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO nic_app.schema_migrations(version) VALUES ('0001_nic_app')
ON CONFLICT (version) DO NOTHING;
COMMIT;
