import { can } from "@/lib/access-control";
import { currentUser, database, enforceRateLimit, requireCsrf } from "@/lib/d1-auth";

const clean=(value:unknown,max=1000)=>typeof value==="string"?value.trim().slice(0,max):"";

export async function GET(request:Request){
  const user=await currentUser(request);if(!user)return Response.json({error:"AUTH_REQUIRED"},{status:401});const db=await database();const providerMember=await db.prepare("SELECT provider_id AS providerId FROM provider_memberships WHERE user_id=? AND status='active'").bind(user.id).first<{providerId:string}>();if(!can(user.role,"work_order:manage")&&!can(user.role,"system:manage_access")&&!can(user.role,"audit:read")&&!providerMember)return Response.json({error:"FORBIDDEN"},{status:403});
  const providerSql=providerMember?db.prepare("SELECT a.id,a.work_order_id AS workOrderId,w.title,a.status,a.response_deadline AS responseDeadline,a.promised_at AS promisedAt,a.response_note AS responseNote,a.version FROM provider_assignments a JOIN maintenance_work_orders w ON w.id=a.work_order_id WHERE a.provider_id=? ORDER BY a.response_deadline").bind(providerMember.providerId):db.prepare("SELECT a.id,a.work_order_id AS workOrderId,w.title,a.status,a.response_deadline AS responseDeadline,a.promised_at AS promisedAt,a.response_note AS responseNote,a.version FROM provider_assignments a JOIN maintenance_work_orders w ON w.id=a.work_order_id ORDER BY a.response_deadline");
  const [slaJobs,slas,closeApprovals,providerDeadlines,accessReviews,reviewItems,resources,templates,changes,notifications]=await Promise.all([db.prepare("SELECT event_type AS eventType,recipient_scope AS recipientScope,created_at AS createdAt FROM sla_job_events ORDER BY created_at DESC LIMIT 50").all(),db.prepare("SELECT s.id,s.work_order_id AS workOrderId,w.title,s.status,s.warning_at AS warningAt,s.due_at AS dueAt,s.pause_reason AS pauseReason FROM sla_instances s JOIN maintenance_work_orders w ON w.id=s.work_order_id ORDER BY s.due_at LIMIT 100").all(),db.prepare("SELECT a.id,a.work_order_id AS workOrderId,w.title,a.status,a.requested_by AS requestedBy,a.requested_at AS requestedAt,a.note FROM work_order_close_approvals a JOIN maintenance_work_orders w ON w.id=a.work_order_id ORDER BY a.requested_at DESC LIMIT 50").all(),providerSql.all(),can(user.role,"system:manage_access")?db.prepare("SELECT id,organization,scope,status,deadline FROM access_reviews ORDER BY deadline LIMIT 50").all():Promise.resolve({results:[]}),can(user.role,"system:manage_access")?db.prepare("SELECT i.id,i.review_id AS reviewId,m.user_id AS userId,u.full_name AS fullName,m.role,i.decision,i.evidence FROM access_review_items i JOIN organization_memberships m ON m.id=i.membership_id JOIN users u ON u.id=m.user_id ORDER BY i.review_id,u.full_name").all():Promise.resolve({results:[]}),db.prepare("SELECT r.id,u.full_name AS fullName,r.location,r.timezone,group_concat(s.skill_code) AS skills FROM resource_profiles r LEFT JOIN users u ON u.id=r.user_id LEFT JOIN resource_skills s ON s.resource_id=r.id WHERE r.status='active' GROUP BY r.id ORDER BY u.full_name").all(),db.prepare("SELECT t.id,t.service_type AS serviceType,t.name,t.version,t.status,count(tt.id) AS taskCount FROM operation_templates t LEFT JOIN operation_template_tasks tt ON tt.template_id=t.id GROUP BY t.id ORDER BY t.service_type,t.version DESC").all(),can(user.role,"system:manage_access")?db.prepare("SELECT id,entity_type AS entityType,entity_id AS entityId,reason,maker_id AS makerId,status,created_at AS createdAt FROM configuration_changes ORDER BY created_at DESC LIMIT 50").all():Promise.resolve({results:[]}),db.prepare("SELECT id,type,title,body,status,created_at AS createdAt FROM notifications WHERE recipient_id=? ORDER BY created_at DESC LIMIT 50").bind(user.id).all()]);
  return Response.json({role:user.role,isProvider:Boolean(providerMember),slaJobs:slaJobs.results,slas:slas.results,closeApprovals:closeApprovals.results,providerDeadlines:providerDeadlines.results,accessReviews:accessReviews.results,reviewItems:reviewItems.results,resources:resources.results,templates:templates.results,changes:changes.results,notifications:notifications.results});
}

export async function POST(request:Request){
  const user=await requireCsrf(request);if(!user)return Response.json({error:"CSRF_INVALID"},{status:403});if(!await enforceRateLimit(request,"operations.p1",user.id,180,3600))return Response.json({error:"RATE_LIMITED"},{status:429});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const action=body?.action,db=await database(),now=Math.floor(Date.now()/1000);
  if(action==="resource_book"){
    if(!can(user.role,"work_order:manage")||user.departmentCode!=="facility")return Response.json({error:"FORBIDDEN"},{status:403});const resourceId=clean(body?.resourceId,80),workOrderId=clean(body?.workOrderId,80),startsAt=Number(body?.startsAt),endsAt=Number(body?.endsAt);if(!resourceId||!workOrderId||!Number.isInteger(startsAt)||!Number.isInteger(endsAt)||endsAt<=startsAt)return Response.json({error:"BOOKING_INVALID"},{status:400});
    const qualified=await db.prepare("SELECT r.id FROM resource_profiles r WHERE r.id=? AND r.status='active' AND NOT EXISTS (SELECT 1 FROM operation_template_tasks ott JOIN work_order_tasks wt ON wt.template_task_id=ott.id WHERE wt.work_order_id=? AND ott.required_skill IS NOT NULL AND NOT EXISTS (SELECT 1 FROM resource_skills s WHERE s.resource_id=r.id AND s.skill_code=ott.required_skill AND (s.valid_until IS NULL OR s.valid_until>=?)))").bind(resourceId,workOrderId,now).first();if(!qualified)return Response.json({error:"RESOURCE_NOT_QUALIFIED"},{status:409});const id=crypto.randomUUID();try{await db.batch([db.prepare("INSERT INTO resource_bookings (id,resource_id,work_order_id,starts_at,ends_at,status,created_at) VALUES (?,?,?,?,?,'confirmed',?)").bind(id,resourceId,workOrderId,startsAt,endsAt,now),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"resource.booked","resource_booking",id,JSON.stringify({resourceId,workOrderId,startsAt,endsAt}),now)]);}catch{return Response.json({error:"RESOURCE_BOOKING_OVERLAP"},{status:409});}return Response.json({id},{status:201});
  }
  if(action==="sla_state"){
    if(!can(user.role,"work_order:manage"))return Response.json({error:"FORBIDDEN"},{status:403});const id=clean(body?.id,80),state=body?.state,reason=clean(body?.reason,500);if(!id||!new Set(["paused","running"]).has(String(state))||(state==="paused"&&!reason))return Response.json({error:"SLA_STATE_INVALID"},{status:400});const current=await db.prepare("SELECT status,paused_at AS pausedAt FROM sla_instances WHERE id=?").bind(id).first<{status:string;pausedAt:number|null}>();if(!current||(state==="paused"&&current.status!=="running")||(state==="running"&&current.status!=="paused"))return Response.json({error:"SLA_TRANSITION_INVALID"},{status:409});const pausedDelta=state==="running"&&current.pausedAt?now-current.pausedAt:0;await db.batch([db.prepare("UPDATE sla_instances SET status=?,paused_at=?,paused_seconds=paused_seconds+?,pause_reason=?,warning_at=warning_at+?,due_at=due_at+?,updated_at=? WHERE id=?").bind(state,state==="paused"?now:null,pausedDelta,state==="paused"?reason:null,pausedDelta,pausedDelta,now,id),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,`sla.${state}`,"sla_instance",id,JSON.stringify({reason,pausedDelta}),now)]);return Response.json({id,status:state});
  }
  if(action==="provider_response"){
    const assignmentId=clean(body?.assignmentId,80),response=body?.response,promisedAt=body?.promisedAt?Number(body.promisedAt):null,note=clean(body?.note,1000);if(!assignmentId||!new Set(["accept","reject","accept_with_change"]).has(String(response))||(response==="accept_with_change"&&(!promisedAt||!note)))return Response.json({error:"PROVIDER_RESPONSE_INVALID"},{status:400});const assignment=await db.prepare("SELECT a.version,a.provider_id AS providerId,a.status FROM provider_assignments a JOIN provider_memberships m ON m.provider_id=a.provider_id AND m.user_id=? AND m.status='active' WHERE a.id=?").bind(user.id,assignmentId).first<{version:number;providerId:string;status:string}>();if(!assignment||assignment.status!=="awaiting_provider")return Response.json({error:"PROVIDER_SCOPE_OR_STATE_INVALID"},{status:403});const version=assignment.version+1,status=response==="accept_with_change"?"awaiting_nic":response==="accept"?"accepted":"rejected";await db.batch([db.prepare("INSERT INTO provider_assignment_responses (id,assignment_id,version,response,promised_at,note,actor_id,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),assignmentId,version,response,promisedAt,note,user.id,now),db.prepare("UPDATE provider_assignments SET version=?,status=?,promised_at=?,response_note=?,responded_by=?,responded_at=? WHERE id=? AND version=?").bind(version,status,promisedAt,note,user.id,now,assignmentId,assignment.version),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"provider.responded","provider_assignment",assignmentId,JSON.stringify({response,version,promisedAt}),now)]);return Response.json({assignmentId,version,status});
  }
  if(action==="configuration_decide"){
    if(!can(user.role,"system:manage_access"))return Response.json({error:"FORBIDDEN"},{status:403});const id=clean(body?.id,80),decision=body?.decision;if(!id||!new Set(["approved","rejected"]).has(String(decision)))return Response.json({error:"DECISION_INVALID"},{status:400});const change=await db.prepare("SELECT maker_id AS makerId FROM configuration_changes WHERE id=? AND status='pending'").bind(id).first<{makerId:string}>();if(!change)return Response.json({error:"CHANGE_NOT_FOUND"},{status:404});if(change.makerId===user.id)return Response.json({error:"MAKER_CANNOT_APPROVE"},{status:409});await db.batch([db.prepare("UPDATE configuration_changes SET status=?,checker_id=?,decided_at=? WHERE id=? AND status='pending'").bind(decision,user.id,now,id),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"configuration.decided","configuration_change",id,JSON.stringify({decision}),now)]);return Response.json({id,status:decision});
  }
  if(action==="provider_confirm"){
    if(!can(user.role,"provider:assign"))return Response.json({error:"FORBIDDEN"},{status:403});const id=clean(body?.id,80),decision=body?.decision;if(!id||!new Set(["accepted","rejected"]).has(String(decision)))return Response.json({error:"DECISION_INVALID"},{status:400});const assignment=await db.prepare("SELECT version,status FROM provider_assignments WHERE id=?").bind(id).first<{version:number;status:string}>();if(!assignment||assignment.status!=="awaiting_nic")return Response.json({error:"ASSIGNMENT_STATE_INVALID"},{status:409});await db.batch([db.prepare("UPDATE provider_assignments SET status=?,confirmed_by=?,confirmed_at=? WHERE id=? AND version=? AND status='awaiting_nic'").bind(decision,user.id,now,id,assignment.version),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"provider.confirmed","provider_assignment",id,JSON.stringify({decision,version:assignment.version}),now)]);return Response.json({id,status:decision});
  }
  if(action==="template_create"){
    if(!can(user.role,"system:manage_access"))return Response.json({error:"FORBIDDEN"},{status:403});const serviceType=clean(body?.serviceType,60),name=clean(body?.name,160),tasks=Array.isArray(body?.tasks)?body.tasks as Array<Record<string,unknown>>:[];if(!serviceType||name.length<3||tasks.length<1||tasks.length>30)return Response.json({error:"TEMPLATE_INVALID"},{status:400});const latest=await db.prepare("SELECT COALESCE(MAX(version),0) AS version FROM operation_templates WHERE service_type=?").bind(serviceType).first<{version:number}>();const id=crypto.randomUUID(),version=(latest?.version??0)+1;const statements=[db.prepare("INSERT INTO operation_templates (id,service_type,name,version,status,created_by,created_at) VALUES (?,?,?,?, 'draft',?,?)").bind(id,serviceType,name,version,user.id,now)];for(let index=0;index<tasks.length;index++){const task=tasks[index],title=clean(task.title,200),skill=clean(task.requiredSkill,80)||null;if(!title)return Response.json({error:"TASK_INVALID"},{status:400});statements.push(db.prepare("INSERT INTO operation_template_tasks (id,template_id,sequence,title,required,estimated_minutes,required_skill,required_materials) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,index+1,title,task.required===false?0:1,Math.max(0,Number(task.estimatedMinutes)||0),skill,JSON.stringify(task.materials??[])));}statements.push(db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"operation_template.created","operation_template",id,JSON.stringify({serviceType,version}),now));await db.batch(statements);return Response.json({id,version,status:"draft"},{status:201});
  }
  if(action==="template_activate"){
    if(!can(user.role,"system:manage_access"))return Response.json({error:"FORBIDDEN"},{status:403});const id=clean(body?.id,80);const template=await db.prepare("SELECT service_type AS serviceType,status FROM operation_templates WHERE id=?").bind(id).first<{serviceType:string;status:string}>();if(!template||template.status!=="draft")return Response.json({error:"TEMPLATE_STATE_INVALID"},{status:409});await db.batch([db.prepare("UPDATE operation_templates SET status='inactive' WHERE service_type=? AND status='active'").bind(template.serviceType),db.prepare("UPDATE operation_templates SET status='active' WHERE id=? AND status='draft'").bind(id),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"operation_template.activated","operation_template",id,JSON.stringify({serviceType:template.serviceType}),now)]);return Response.json({id,status:"active"});
  }
  if(action==="configuration_propose"){
    if(!can(user.role,"system:manage_access"))return Response.json({error:"FORBIDDEN"},{status:403});const entityType=body?.entityType,entityId=clean(body?.entityId,100),reason=clean(body?.reason,1000),payload=body?.payload;if(!new Set(["role","sla","master_data"]).has(String(entityType))||!entityId||!reason||typeof payload!=="object")return Response.json({error:"CHANGE_INVALID"},{status:400});const id=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO configuration_changes (id,entity_type,entity_id,payload,reason,maker_id,status,created_at) VALUES (?,?,?,?,?,?,'pending',?)").bind(id,entityType,entityId,JSON.stringify(payload),reason,user.id,now),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"configuration.proposed","configuration_change",id,JSON.stringify({entityType,entityId}),now)]);return Response.json({id,status:"pending"},{status:201});
  }
  if(action==="access_review_create"){
    if(!can(user.role,"system:manage_access"))return Response.json({error:"FORBIDDEN"},{status:403});const organization=clean(body?.organization,160),scope=clean(body?.scope,160),deadline=Number(body?.deadline);if(!organization||!scope||!Number.isInteger(deadline)||deadline<=now)return Response.json({error:"REVIEW_INVALID"},{status:400});const id=crypto.randomUUID();const memberships=(await db.prepare("SELECT id FROM organization_memberships WHERE organization=? AND status='active'").bind(organization).all<{id:string}>()).results;const statements=[db.prepare("INSERT INTO access_reviews (id,organization,scope,status,deadline,created_by,created_at) VALUES (?,?,?,'open',?,?,?)").bind(id,organization,scope,deadline,user.id,now),...memberships.map(item=>db.prepare("INSERT INTO access_review_items (id,review_id,membership_id) VALUES (?,?,?)").bind(crypto.randomUUID(),id,item.id)),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"access_review.created","access_review",id,JSON.stringify({organization,scope,count:memberships.length}),now)];await db.batch(statements);return Response.json({id,itemCount:memberships.length,status:"open"},{status:201});
  }
  if(action==="access_review_decide"){
    if(!can(user.role,"system:manage_access"))return Response.json({error:"FORBIDDEN"},{status:403});const itemId=clean(body?.itemId,80),decision=body?.decision,evidence=clean(body?.evidence,2000);if(!itemId||!new Set(["retain","revoke"]).has(String(decision))||!evidence)return Response.json({error:"REVIEW_DECISION_INVALID"},{status:400});const item=await db.prepare("SELECT membership_id AS membershipId FROM access_review_items WHERE id=? AND decision IS NULL").bind(itemId).first<{membershipId:string}>();if(!item)return Response.json({error:"REVIEW_ITEM_NOT_FOUND"},{status:404});const statements=[db.prepare("UPDATE access_review_items SET decision=?,evidence=?,reviewed_by=?,reviewed_at=? WHERE id=? AND decision IS NULL").bind(decision,evidence,user.id,now,itemId),db.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),user.id,"access_review.decided","access_review_item",itemId,JSON.stringify({decision,evidence}),now)];if(decision==="revoke")statements.push(db.prepare("UPDATE organization_memberships SET status='revoked' WHERE id=?").bind(item.membershipId),db.prepare("DELETE FROM sessions WHERE user_id=(SELECT user_id FROM organization_memberships WHERE id=?)").bind(item.membershipId));await db.batch(statements);return Response.json({itemId,decision});
  }
  return Response.json({error:"ACTION_INVALID"},{status:400});
}
