import { database } from "@/lib/d1-auth";

type SlaRow={id:string;warningAt:number;dueAt:number;priority:string};

export async function POST(request:Request){
  const secret=process.env.SLA_CRON_SECRET;if(!secret||request.headers.get("authorization")!==`Bearer ${secret}`)return Response.json({error:"UNAUTHORIZED"},{status:401});
  const db=await database(),now=Math.floor(Date.now()/1000);const instances=(await db.prepare("SELECT s.id,s.warning_at AS warningAt,s.due_at AS dueAt,w.priority FROM sla_instances s JOIN maintenance_work_orders w ON w.id=s.work_order_id WHERE s.status='running' AND s.warning_at<=?").bind(now).all<SlaRow>()).results;let emitted=0;
  for(const item of instances){const eventType=now>=item.dueAt?"failure":"warning",key=`${item.id}:${eventType}:${eventType==="failure"?item.dueAt:item.warningAt}`,scope=item.priority==="critical"?"facility_manager,service_desk":"facility_manager";const result=await db.prepare("INSERT INTO sla_job_events (id,sla_instance_id,event_type,idempotency_key,recipient_scope,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT(idempotency_key) DO NOTHING").bind(crypto.randomUUID(),item.id,eventType,key,scope,now).run();if(result.meta.changes){emitted+=1;await db.prepare("INSERT INTO notifications (id,recipient_id,type,entity_type,entity_id,dedupe_key,title,body,created_at) SELECT lower(hex(randomblob(16))),u.id,?,'sla_instance',?,? || ':' || u.id,?,?,? FROM users u WHERE u.role IN ('facility_manager',?) ON CONFLICT(dedupe_key) DO NOTHING").bind(`sla_${eventType}`,item.id,key,eventType==="failure"?'SLA đã vi phạm':'SLA sắp đến hạn',`Ưu tiên ${item.priority}`,now,item.priority==="critical"?'service_desk':'facility_manager').run();}if(eventType==="failure")await db.prepare("UPDATE sla_instances SET status='failed',updated_at=? WHERE id=? AND status='running'").bind(now,item.id).run();}
  const expired=await db.prepare("UPDATE provider_assignments SET status='expired' WHERE status='awaiting_provider' AND response_deadline<=?").bind(now).run();
  const overdueReviews=await db.prepare("UPDATE access_reviews SET status='overdue' WHERE status='open' AND deadline<=?").bind(now).run();
  if(overdueReviews.meta.changes)await db.prepare("INSERT INTO notifications (id,recipient_id,type,entity_type,entity_id,dedupe_key,title,body,created_at) SELECT lower(hex(randomblob(16))),u.id,'access_review_overdue','access_review',r.id,'access-review-overdue:' || r.id || ':' || u.id,'Access review quá hạn',r.organization || ' · ' || r.scope,? FROM access_reviews r JOIN users u ON u.role='system_admin' WHERE r.status='overdue' ON CONFLICT(dedupe_key) DO NOTHING").bind(now).run();
  return Response.json({checked:instances.length,emitted,expiredProviderAssignments:expired.meta.changes,overdueReviews:overdueReviews.meta.changes,ranAt:now});
}
